import json, re

# Deep, meaningful etymology and mnemonic hook dictionary
# Every entry MUST explain the logical connection between the root/parts and the meaning, or give a vivid memory story.

ETEMY_DICTIONARY = {
    # R
    "refrigerator": "re- (反复) + frig (冷/冻，同源fridge) + -ate (使...) + -or (器具) ➔ 反复保持低温冰冻的机器 ➔ (电)冰箱",
    "ready": "read (读/理清) + -y ➔ 事情读清整理完毕状态 ➔ adj. 准备好的",
    "realize": "real (真实) + -ize (使...) ➔ 使脑海想法变为真实 ➔ v. 实现;意识到",
    "recently": "recent (最近的) + -ly ➔ 近期地 ➔ adv. 最近",
    "receive": "re- (回) + ceive (拿/接) ➔ 接拿回递来的物品 ➔ v. 收到;接收",
    "record": "re- (再次) + cord (心灵) ➔ 再次记入心间/记载 ➔ v. 记录 n. 唱片;记录",
    "recover": "re- (重新) + cover (盖上/保护) ➔ 重新获得健康保护 ➔ v. 恢复;痊愈",
    "reduce": "re- (向后) + duce (引导/拉) ➔ 向后拉回降低数量 ➔ v. 减少;降低",
    "refer": "re- (向后/再次) + fer (带来/提交) ➔ 带来意见做参考 ➔ v. 参考;查阅;提及",
    "reflect": "re- (反/回) + flect (弯曲/折射) ➔ 光线反弹弯折过来 ➔ v. 反射;反映;沉思",
    "reform": "re- (重新) + form (形状/规范) ➔ 重新塑造成新规范 ➔ v./n. 改革;改进",
    "refuse": "re- (向后) + fuse (倾倒) ➔ 把东西往回倒掉不接受 ➔ v. 拒绝;推辞",
    "regard": "re- (强调) + gard (看护/目光) ➔ 投以重视注视的目光 ➔ v. 看待;重视 n. 问候",
    "regret": "re- (反复) + gret (哭泣/哀叹) ➔ 事后反复哀叹痛惜 ➔ v./n. 遗憾;后悔",
    "regular": "regul (规则/尺子) + -ar ➔ 符合规矩尺度的 ➔ adj. 有规律的;定期/常规的",
    "regulation": "regul (规则) + -ation ➔ 约束行为的规章制度 ➔ n. 规则;规定;调节",
    "reject": "re- (向后) + ject (扔) ➔ 向后扔回去不接受 ➔ v. 拒绝;驳回",
    "relate": "re- (回) + lat (带来/联系) ➔ 带回联系起来 ➔ v. 有联系;叙述",
    "relation": "relate (联系) + -ion ➔ 人与人之间的联系关系 ➔ n. 关系;亲戚",
    "relationship": "relation (关系) + -ship (资格/状态) ➔ 彼此紧密相连的关系 ➔ n. 关系;关联",
    "relative": "relate (联系) + -ive (人) ➔ 有血缘联系的人 ➔ n. 亲戚 adj. 相对的",
    "relax": "re- (松开) + lax (松弛) ➔ 彻底松弛下来 ➔ v. 放松;休息",
    "release": "re- (解开) + lease (松开) ➔ 解开束缚释放 ➔ v./n. 释放;发布;发行",
    "relevant": "re- (再次) + lev (举起/相关) + -ant ➔ 能拿来证明相关的 ➔ adj. 相关的;切题的",
    "reliable": "re- (强调) + li (绑定/依靠) + -able ➔ 值得绑定依靠的 ➔ adj. 可靠的;可信赖的",
    "relief": "re- (下) + lief (轻) ➔ 卸下重担心里变轻 ➔ n. 解脱;轻松;救济",
    "relieve": "re- (下) + lieve (轻) ➔ 使心里重担变轻 ➔ v. 减轻;缓解;使宽慰",
    "religion": "re- (重新) + lig (绑定) + -ion ➔ 将心灵与神明绑定在一起 ➔ n. 宗教;信仰",
    "religious": "religion (宗教) + -ious ➔ 虔诚信仰宗教的 ➔ adj. 宗教的;虔诚的",
    "reluctant": "re- (反) + luct (挣扎) + -ant ➔ 内心反复挣扎不情愿的 ➔ adj. 不情愿的;勉强的",
    "rely": "re- (强调) + ly (绑定/依靠) ➔ 绑定在对方身上 ➔ v. 依靠;依赖",
    "remain": "re- (在后) + main (停留) ➔ 留在后面不离开 ➔ v. 保持;剩余;留存",
    "remind": "re- (再次) + mind (心灵/脑海) ➔ 再次唤起脑海记忆 ➔ v. 提醒;使想起",
    "remote": "re- (向后) + mot (移动) + -e ➔ 向后退移得极远的 ➔ adj. 偏远的;遥远的",
    "remove": "re- (离开) + move (移动) ➔ 移动移开 ➔ v. 移走;消除;免职",
    "repair": "re- (重新) + pair (准备/修整) ➔ 重新整理好破损 ➔ v./n. 修理;修补",
    "repeat": "re- (再次) + peat (追求/寻求) ➔ 再次做同样的事情 ➔ v./n. 重复;重做",
    "replace": "re- (替代) + place (位置) ➔ 换个新的占据原位置 ➔ v. 替换;取代",
    "reply": "re- (反/回) + ply (折叠/回答) ➔ 递回对折的信件回复 ➔ v./n. 回复;答复",
    "report": "re- (带回) + port (运送) ➔ 将现场情况带回来汇报 ➔ v./n. 报告;报道",
    "represent": "re- (再次) + present (呈现) ➔ 再次呈现在大众面前代表 ➔ v. 代表;呈现",
    "reputation": "re- (反复) + put (思考/衡量) + -ation ➔ 大家反复推崇的高名望 ➔ n. 名声;声誉",
    "request": "re- (再次) + quest (寻求/询问) ➔ 郑重提出寻求请求 ➔ v./n. 请求;要求",
    "require": "re- (强调) + quire (寻求) ➔ 强烈索求必须具备 ➔ v. 需要;要求",
    "research": "re- (反复) + search (搜寻) ➔ 深入反复探索调查 ➔ n./v. 研究;调查",
    "resemble": "re- (强调) + sembl (相像) ➔ 看起来十分相像 ➔ v. 与……相似;像",
    "reserve": "re- (预先) + serv (留存/保存) ➔ 预先保存留待后用 ➔ v. 预订;保留 n. 储备",
    "reset": "re- (重新) + set (设置) ➔ 重新清零设置 ➔ v./n. 重置;复位",
    "resign": "re- (放弃) + sign (签名) ➔ 签署离职协议辞职 ➔ v. 辞职;放弃",
    "resist": "re- (反) + sist (站立) ➔ 站出来反抗抵制 ➔ v. 抵抗;抵制",
    "resolve": "re- (强调) + solve (解开) ➔ 彻底解开难题下决心 ➔ v. 解决;下决心",
    "resource": "re- (再次) + source (源头) ➔ 源源不断涌现的资源 ➔ n. 资源;物力",
    "respect": "re- (反复) + spect (看) ➔ 令人肃然起敬反复注视 ➔ v./n. 尊敬;尊重",
    "respond": "re- (反/回) + spond (承诺/回答) ➔ 做出回应答复 ➔ v. 回答;响应",
    "responsible": "respond (响应/承担) + -ible ➔ 能够承担后果的 ➔ adj. 负责任的",
    "rest": "源自停下休息 ➔ 歇息/其余 ➔ n./v. 休息;其余部分",
    "restaurant": "rest (休息) + aur (恢复) + -ant ➔ 恢复体力用餐休息的小店 ➔ n. 饭店;餐厅",
    "restore": "re- (再次) + store (放置/建立) ➔ 重建恢复原状 ➔ v. 恢复;修复",
    "restrict": "re- (向后) + strict (拉紧) ➔ 向后拉紧约束范围 ➔ v. 限制;约束",
    "result": "re- (向后) + sult (跳) ➔ 最终跳出来的结案结局 ➔ n. 结果 v. 产生",
    "resume": "re- (重新) + sume (拿) ➔ 重新拿起做或个人履历 ➔ v. 恢复;重新开始 n. 简历",
    "retain": "re- (保持) + tain (拿住) ➔ 紧紧留存保留 ➔ v. 保留;保持",
    "retire": "re- (向后) + tire (拉/抽离) ➔ 抽离工作岗位退休 ➔ v. 退休;退役",
    "return": "re- (回) + turn (转) ➔ 转头返回 ➔ v./n. 返回;归还",
    "reveal": "re- (反/揭开) + veil (面纱) ➔ 揭开面纱泄露真相 ➔ v. 揭露;泄露",
    "revenge": "re- (反) + venge (惩罚/复仇) ➔ 反击惩罚对方 ➔ v./n. 报复;复仇",
    "reverse": "re- (反) + vers (转) ➔ 朝相反方向颠倒反转 ➔ v./adj. 反转;颠倒的",
    "review": "re- (再次) + view (看) ➔ 再次温习查看 ➔ v./n. 复习;审查;评论",
    "revise": "re- (再次) + vis (看) ➔ 再次审视修改校订 ➔ v. 修改;校订",
    "revive": "re- (再次) + viv (生命) + -e ➔ 重获新生复苏 ➔ v. 苏醒;复兴",
    "revolution": "revolt (翻转) + -ution ➔ 天翻地覆的革命 ➔ n. 革命;剧变",
    "reward": "re- (再次) + ward (注意/守护) ➔ 给予丰厚赏赐报酬 ➔ n./v. 报酬;奖赏",
    "rhythm": "rhyth (流动) + -m ➔ 像水流般有规律的节奏 ➔ n. 节奏;韵律",
    "rich": "源自强盛富足 ➔ 富有的 ➔ adj. 富有的;丰富的",
    "rid": "源自清除摆脱 ➔ 摆脱除去 ➔ v. 使摆脱;清除",
    "ride": "源自骑马出行 ➔ 骑乘 ➔ v./n. 骑;乘车",
    "ridge": "源自脊背 ➔ 山脊;垄 ➔ n. 山脊;隆起",
    "ridiculous": "rid (笑) + -iculous ➔ 荒谬可笑的 ➔ adj. 荒谬的;可笑的",
    "rigid": "rig (僵硬) + -id ➔ 僵硬死板的 ➔ adj. 严格的;死板的",
    "ring": "源自圆圈响铃 ➔ 戒指/铃声 ➔ n. 戒指;铃声 v. 按铃;响",
    "ripe": "源自成熟剥壳 ➔ 瓜熟蒂落成熟的 ➔ adj. 成熟的",
    "rise": "源自向上升起 ➔ 升起;上涨 ➔ v./n. 上升;增加",
    "risk": "源自悬崖峭壁险境 ➔ 冒险/风险 ➔ n./v. 风险;冒……风险",
    "rival": "riv (河流) + -al ➔ 隔河相对竞争的对手 ➔ n. 对手 v. 竞争",
    "river": "riv (流动) + -er ➔ 水流奔涌的河流 ➔ n. 河流;江",
    "road": "源自驾车骑行之道 ➔ 道路 ➔ n. 道路;公路",
    "rob": "源自抢掠衣物 ➔ 抢劫盗窃 ➔ v. 抢劫;剥夺",
    "robot": "rob (苦力/奴隶) + -ot ➔ 代替做苦力的机器人 ➔ n. 机器人",
    "rock": "源自岩石摇晃 ➔ 摇滚/岩石 ➔ n. 岩石;摇滚乐 v. 摇晃",
    "rocket": "rock (纺锤) + -et (小) ➔ 飞快发射的火箭 ➔ n. 火箭 v. 飞升",
    "rod": "源自细长树枝 ➔ 杆;棒 ➔ n. 杆;棒;钓竿",
    "role": "rot (卷轴/剧本) ➔ 演戏扮演的角色 ➔ n. 角色;作用",
    "roll": "rot (圆圈) + -l ➔ 滚动卷动 ➔ v./n. 滚动;卷;名册",
    "romantic": "Rome (罗马浪漫传奇) + -tic ➔ 充满浪漫情调的 ➔ adj. 浪漫的;传奇的",
    "root": "源自植物根系 ➔ 根源/根 ➔ n. 根;根源 v. 生根",
    "rope": "源自编织绳索 ➔ 绳索 ➔ n. 绳索 v. 捆绑",
    "rough": "源自粗糙不平 ➔ 粗糙的/大致的 ➔ adj. 粗糙的;艰难的;大致的",
    "round": "rot (圆) + -und ➔ 圆形的 ➔ adj. 圆的 adv. 围绕 prep. 环绕",
    "route": "rupt (打破/破开路) ➔ 破开开辟出的路线 ➔ n. 路线;航线",
    "routine": "route (路线/惯例) + -ine ➔ 每天例行公事的流程 ➔ n. 例行公事;日常作息",
    "row": "源自划船排队列 ➔ 一排/划船 ➔ n. 一排 v. 划船",
    "royal": "rex/reg (国王) + -al ➔ 皇室王室的 ➔ adj. 王室的;皇家的",
    "rub": "源自摩擦擦拭 ➔ 摩擦 ➔ v./n. 摩擦;擦拭",
    "rubber": "rub (擦) + -er (物) ➔ 用来擦除墨迹的橡皮/橡胶 ➔ n. 橡胶;橡皮",
    "rubbish": "rub (擦刮出的废弃物) + -ish ➔ 垃圾废品 ➔ n. 垃圾;废话",
    "rude": "rud (原始/粗鲁) + -e ➔ 粗鲁无礼的 ➔ adj. 粗鲁的;无礼的",
    "ruin": "ru (倒塌) + -in ➔ 毁坏废墟 ➔ v./n. 毁灭;废墟",
    "rule": "regul (尺子/规则) ➔ 规矩规则 ➔ n. 规则;统治 v. 规则;统治",
    "ruler": "rule (统治/量尺) + -er ➔ 统治者或直尺 ➔ n. 统治者;直尺",
    "rumor": "rum (流言) + -or ➔ 坊间流传的谣言 ➔ n. 谣言;传闻",
    "run": "源自奔跑流动 ➔ 奔跑/运转 ➔ v. 奔跑;经营;运转",
    "rural": "rus (乡村) + -al ➔ 乡村农村的 ➔ adj. 乡村的;农村的",
    "rush": "源自急冲冲刺 ➔ 冲刺/忙碌 ➔ v./n. 冲;奔;急促",
    "rust": "源自红褐色氧化层 ➔ 生锈 ➔ n. 铁锈 v. 生锈",
    
    # S
    "sacred": "sacr (神圣) + -ed ➔ 神圣不可侵犯的 ➔ adj. 神圣的;宗教的",
    "sacrifice": "sacr (神圣) + fic (做) ➔ 献给神明的祭品/牺牲 ➔ n./v. 牺牲;祭品",
    "sad": "源自饱足/沉重 ➔ 情绪沉重悲伤的 ➔ adj. 悲伤的;难过的",
    "safe": "salv (拯救/安全) ➔ 平安无事安全的 ➔ adj. 安全的 n. 保险箱",
    "safety": "safe (安全) + -ty ➔ 安全保障状态 ➔ n. 安全;平安",
    "sail": "源自风帆航行 ➔ 航行 ➔ v./n. 航行;帆",
    "sailor": "sail (航行) + -or (人) ➔ 水手海员 ➔ n. 水手;海员",
    "sake": "源自争论/利益 ➔ 为了……的缘故利益 ➔ n. 缘故;利益",
    "salary": "sal (盐/古罗马发给士兵买盐的津贴) ➔ 固定薪水工资 ➔ n. 薪水;工资",
    "sale": "sell (卖) + -e ➔ 销售出售 ➔ n. 出售;销售额",
    "salt": "sal (盐) ➔ 食盐 ➔ n. 盐 v. 加盐",
    "same": "sem (同一) + -e ➔ 一模一样的 ➔ adj. 相同的 pron. 同样的人/事",
    "sample": "ex- (出) + emp (拿) ➔ 拿出来展示的样品 ➔ n. 样品;样本 v. 抽样",
    "sand": "源自沙粒海滩 ➔ 沙子 ➔ n. 沙;沙滩",
    "satellite": "satell (随从/侍从) + -ite ➔ 围绕主星运转的人造卫星 ➔ n. 人造卫星",
    "satisfaction": "satisfy (满足) + -ion ➔ 内心感受到的满意 ➔ n. 满意;满足",
    "satisfy": "satis (足够) + -ify (使) ➔ 使感到足够满意 ➔ v. 使满意;满足",
    "sauce": "sals (咸/调味) ➔ 酱汁调味汁 ➔ n. 酱汁;调味料",
    "save": "salv (拯救/保留) ➔ 拯救/节省 ➔ v. 救;节省;储蓄",
    "say": "源自说话言语 ➔ 说话 ➔ v. 说;讲",
    "scale": "scand (攀登/刻度) ➔ 刻度/规模 ➔ n. 规模;刻度;秤",
    "scan": "scand (攀登/细查) ➔ 快速扫描细查 ➔ v./n. 扫描;浏览",
    "scandal": "scandal (陷阱/丑闻) ➔ 令人发指的丑闻 ➔ n. 丑闻;耻辱",
    "scarcely": "scarce (稀少) + -ly ➔ 几乎不/简直没有 ➔ adv. 几乎不;简直没有",
    "scare": "源自恐吓惊吓 ➔ 惊吓 ➔ v./n. 惊吓;恐慌",
    "scene": "scen (舞台) + -e ➔ 现场景象 ➔ n. 现场;景象;情景",
    "schedule": "scheda (小纸片/明细) ➔ 时间行程表 ➔ n. 时间表;日程安排 v. 安排",
    "scheme": "schem (方案/图形) ➔ 策划的方案计划 ➔ n. 方案;计划;阴谋",
    "scholar": "schol (学校/闲暇) ➔ 潜心学术的学者 ➔ n. 学者;奖学金获得者",
    "scholarship": "scholar (学者) + -ship ➔ 资助优秀学者的奖学金 ➔ n. 奖学金;学术成就",
    "school": "schol (闲暇/探讨学术) ➔ 学校 ➔ n. 学校;学派",
    "science": "sci (知道/知识) + -ence ➔ 探索规律的科学 ➔ n. 科学;学科",
    "scientific": "science (科学) + -fic (做) ➔ 符合科学规律的 ➔ adj. 科学的",
    "scientist": "sci (知道) + -ist (学者) ➔ 探索科学的人 ➔ n. 科学家",
    "scope": "scop (看/观察) ➔ 视野关注的范围 ➔ n. 范围;眼界",
    "score": "scor (刻痕记分) ➔ 得分/分数 ➔ n. 得分;分数 v. 得分",
    "scream": "源自尖叫呼喊 ➔ 尖叫 ➔ v./n. 尖叫;大喊",
    "screen": "源自屏风遮挡 ➔ 屏幕 ➔ n. 屏幕;屏风 v. 筛选;遮挡",
    "script": "script (书写) ➔ 写出的剧本手稿 ➔ n. 剧本;手稿;脚本",
    "sea": "源自大海水域 ➔ 海洋 ➔ n. 海洋;大海",
    "search": "circ (圆圈/搜寻) ➔ 四处搜寻寻找 ➔ v./n. 搜索;寻找",
    "season": "sow (播种期) + -on ➔ 季节 ➔ n. 季节;赛季 v. 加调味料",
    "seat": "sed/sit (坐) + -t ➔ 座位 ➔ n. 座位 v. 使就座",
    "second": "sequ (跟随) + -ond ➔ 跟在第一后面的第二 ➔ num. 第二 n. 秒",
    "secondary": "second (第二) + -ary ➔ 次要的/中等的 ➔ adj. 次要的;中等的",
    "secret": "se- (分开) + cret (筛选/隐藏) ➔ 藏起来的秘密 ➔ adj. 秘密的 n. 秘密",
    "secretary": "secret (秘密) + -ary (人) ➔ 掌管机密文书的秘书 ➔ n. 秘书;干事",
    "section": "sect (切) + -ion ➔ 切分出的章节/部门 ➔ n. 章节;部门;截面",
    "sector": "sect (切) + -or ➔ 划分出的经济部门 ➔ n. 部门;领域",
    "secure": "se- (离开) + cur (忧虑) ➔ 无忧无虑安全的 ➔ adj. 安全的 v. 获得;确保",
    "security": "secure (安全) + -ity ➔ 安全保障 ➔ n. 安全;平安;证券",
    "see": "源自用眼注视 ➔ 看见 ➔ v. 看见;明白;领会",
    "seed": "sow (播种) + -d ➔ 种子 ➔ n. 种子 v. 播种",
    "seek": "源自寻求追寻 ➔ 寻找/谋求 ➔ v. 寻找;追求",
    "seem": "sem (相同/适合) ➔ 显得/好像 ➔ v. 似乎;好像",
    "segment": "seg (切) + -ment ➔ 切割出的片段 ➔ n. 片段;部分",
    "select": "se- (分开) + lect (挑选) ➔ 精选挑选出来 ➔ v. 挑选;选择 adj. 精选的",
    "selection": "select (挑选) + -ion ➔ 挑选出的选项 ➔ n. 选择;精选",
    "self": "源自自己个人 ➔ 自己/自我 ➔ n. 自己;自我",
    "sell": "源自交付交易 ➔ 卖/销售 ➔ v. 出售;售卖",
    "semester": "six (六) + menses (月份) ➔ 半年一期的学期 ➔ n. 学期",
    "send": "源自派遣发送 ➔ 送出/发送 ➔ v. 发送;派遣",
    "senior": "sen (年老) + -ior ➔ 资深的/长辈 ➔ adj. 资深的;高级的 n. 长辈",
    "sense": "sens (感觉/理智) ➔ 感觉/理智 ➔ n. 感官;理智;意义 v. 感觉到",
    "sensible": "sens (理智) + -ible ➔ 通情达理明智的 ➔ adj. 明智的;通情达理的",
    "sensitive": "sens (感觉) + -ive ➔ 敏感易受影响的 ➔ adj. 敏感的;体贴的",
    "sentence": "sens (想法/判决) + -ence ➔ 表达完整意思的句子或审判 ➔ n. 句子;判决 v. 宣判",
    "separate": "se- (分开) + par (准备) + -ate ➔ 分离开来 ➔ adj. 分开的 v. 分离",
    "sequence": "sequ (跟随) + -ence ➔ 紧紧跟随的序列 ➔ n. 序列;顺序",
    "series": "ser (连接) + -ies ➔ 串联起来的一系列 ➔ n. 系列;连续剧",
    "serious": "ser (严肃) + -ious ➔ 严肃严重的 ➔ adj. 严重的;严肃的",
    "servant": "serv (服务) + -ant (人) ➔ 供仆役服务的人 ➔ n. 仆人;公务员",
    "serve": "serv (服务/侍候) ➔ 服务/供职 ➔ v. 服务;招待;提供",
    "service": "serv (服务) + -ice ➔ 公共服务 ➔ n. 服务;公共机构",
    "session": "sess (坐) + -ion ➔ 开会坐在一起的会期 ➔ n. 会议;会期;学期",
    "set": "源自放置摆放 ➔ 放置/设定 ➔ v. 放置;设置 n. 一套",
    "settle": "set (放置/定居) + -le ➔ 定居/解决 ➔ v. 解决;定居;安顿",
    "settlement": "settle (定居) + -ment ➔ 定居点或协议结算 ➔ n. 定居点;协议;结算",
    "seven": "源自数字7 ➔ 七 ➔ num. 七",
    "several": "se- (分开) + ver (转) + -al ➔ 若干个各自独立的 ➔ adj./pron. 几个;若干",
    "severe": "源自严厉苛刻 ➔ 极其严重的 ➔ adj. 严重的;严厉的",
    "shadow": "shade (阴影) + -ow ➔ 影子/阴影 ➔ n. 影子;阴影",
    "shake": "源自摇晃震动 ➔ 摇动/握手 ➔ v./n. 摇动;握手",
    "shall": "源自应当必须 ➔ 将要/应当 ➔ aux. 将要;应该",
    "shallow": "源自浅水不深 ➔ 浅的/肤浅的 ➔ adj. 浅的;肤浅的",
    "shame": "源自遮掩羞耻 ➔ 羞愧/遗憾 ➔ n. 羞耻;遗憾",
    "shape": "源自塑造外形 ➔ 形状/外形 ➔ n. 形状 v. 塑造",
    "share": "shear (剪下切开) ➔ 切下一份共享 ➔ v. 分享;共享 n. 股份",
    "sharp": "源自锋利刺人 ➔ 锋利的/急剧的 ➔ adj. 锋利的;敏锐的;急剧的",
    "she": "源自女性代词 ➔ 她 ➔ pron. 她",
    "sheep": "源自绵羊 ➔ 绵羊 ➔ n. 绵羊 (单复同)",
    "sheet": "源自展开的一张 ➔ 薄片/床单/纸张 ➔ n. 一张;床单;表格",
    "shelf": "源自木板架子 ➔ 架子/书架 ➔ n. 架子;书架",
    "shelter": "shield (盾牌) + -er ➔ 避难所/庇护 ➔ n. 避难所 v. 庇护",
    "shine": "源自发光闪耀 ➔ 发光/照耀 ➔ v. 发光;照耀 n. 光泽",
    "ship": "源自船只航行 ➔ 船/运送 ➔ n. 船 v. 运输",
    "shirt": "short (短衣) ➔ 衬衫 ➔ n. 衬衫",
    "shock": "源自撞击震惊 ➔ 震惊/震动 ➔ n./v. 震惊;休克;冲突",
    "shoe": "源自鞋子脚套 ➔ 鞋 ➔ n. 鞋",
    "shoot": "源自射击发射 ➔ 射击/拍摄 ➔ v. 射击;拍摄;发芽",
    "shop": "源自店铺车间 ➔ 商店/购物 ➔ n. 商店 v. 购物",
    "shore": "shear (切断/陆地边缘) ➔ 岸/滨 ➔ n. 岸;海滨",
    "short": "源自截短的 ➔ 短的/矮的 ➔ adj. 短的;矮的;缺乏的",
    "shortage": "short (短缺) + -age ➔ 短缺/不足 ➔ n. 短缺;不足",
    "should": "shall (应当) 过去式 ➔ 应该 ➔ aux. 应该",
    "shoulder": "源自肩膀 ➔ 肩膀 ➔ n. 肩膀 v. 承担",
    "shout": "源自大声呼喊 ➔ 喊叫 ➔ v./n. 大声喊",
    "show": "源自展示给人看 ➔ 展示/表演 ➔ v. 展示;表明 n. 表演;展览",
    "shrink": "源自收缩变小 ➔ 收缩/缩小 ➔ v. 收缩;缩小",
    "shut": "源自关上门窗 ➔ 关闭 ➔ v. 关上;关闭 adj. 关闭的",
    "shy": "源自避开害羞 ➔ 害羞的 ➔ adj. 害羞的;胆小的",
    "sick": "源自患病呕吐 ➔ 有病的/恶心的 ➔ adj. 有病的;恶心的",
    "side": "源自侧面边沿 ➔ 侧面/立场 ➔ n. 侧面;边缘;立场",
    "sigh": "源自叹气叹息 ➔ 叹气 ➔ v./n. 叹气;叹息",
    "sight": "see (看) + -t ➔ 视力/风景 ➔ n. 视力;视线;风景",
    "sign": "sign (标记/记号) ➔ 标志/签名 ➔ n. 标志;迹象 v. 签名",
    "signal": "sign (标记) + -al ➔ 信号 ➔ n. 信号 v. 发信号",
    "signature": "sign (签名) + -ature ➔ 亲笔签名 ➔ n. 签名;署名",
    "significance": "sign (标记) + fic (做) ➔ 极具象征意义的重要性 ➔ n. 重要性;意义",
    "significant": "sign (标记) + fic (做) + -ant ➔ 有重大意义的 ➔ adj. 显著的;重大的",
    "silence": "sil (安静) + -ence ➔ 寂静无声 ➔ n. 沉默;寂静",
    "silent": "sil (安静) + -ent ➔ 沉默安静的 ➔ adj. 沉默的;无声的",
    "silly": "源自幼稚愚蠢 ➔ 愚蠢的 ➔ adj. 愚蠢的;傻的",
    "silver": "源自白银贵金属 ➔ 银/银白色的 ➔ n. 银 adj. 银色的",
    "similar": "simil (相像) + -ar ➔ 相似的 ➔ adj. 相似的;类似的",
    "simple": "sim- (单一) + ple (折叠) ➔ 未经复杂折叠简单纯粹的 ➔ adj. 简单的;朴素的",
    "simplify": "simple (简单) + -ify (使) ➔ 使变得简单易懂 ➔ v. 简化;使精简",
    "since": "sithen (自……以后) ➔ 自……以来 ➔ prep./conj. 自从;因为",
    "sincere": "sin (纯粹) + cere (蜡) ➔ 无假蜡装饰的真诚 ➔ adj. 真诚的;诚挚的",
    "sing": "源自吟唱唱歌 ➔ 唱歌 ➔ v. 唱歌",
    "single": "singul (单一) ➔ 单个的/单身的 ➔ adj. 单一的;单身的",
    "singular": "singul (单一) + -ar ➔ 单数的/非凡的 ➔ adj. 单数的;非凡的",
    "sink": "源自沉没下沉 ➔ 沉没/水槽 ➔ v. 下沉 n. 水槽",
    "sir": "senior (长者/尊称) ➔ 先生/阁下 ➔ n. 先生;阁下",
    "sister": "源自姐妹 ➔ 姐妹 ➔ n. 姐;妹",
    "sit": "sed/sit (坐) ➔ 坐下 ➔ v. 坐;位于",
    "site": "sit (位置/坐) ➔ 场所/地点 ➔ n. 地点;场所;遗址",
    "situation": "sit (位置/处境) + -uation ➔ 局势/处境 ➔ n. 局势;状况",
    "six": "源自数字6 ➔ 六 ➔ num. 六",
    "size": "assize (测量评估出的尺寸) ➔ 尺寸/大小 ➔ n. 尺寸;大小",
    "skill": "skel (切分/辨别技巧) ➔ 技能/技巧 ➔ n. 技能;技巧",
    "skin": "源自剥皮皮肤 ➔ 皮肤/皮 ➔ n. 皮肤;外皮",
    "skirt": "short (短裙) ➔ 裙子 ➔ n. 裙子",
    "sky": "源自天空云彩 ➔ 天空 ➔ n. 天空",
    "sleep": "源自闭眼睡眠 ➔ 睡觉 ➔ v./n. 睡觉;睡眠",
    "slight": "源自轻微细小 ➔ 轻微的/纤细的 ➔ adj. 轻微的;纤细的",
    "slip": "源自滑倒滑落 ➔ 滑倒/溜走 ➔ v. 滑倒;溜走 n. 差错",
    "slow": "源自迟缓慢速 ➔ 缓慢的 ➔ adj. 慢的 v. 减速",
    "small": "源自细微狭小 ➔ 小的/微少的 ➔ adj. 小的;少的",
    "smart": "源自刺痛/敏捷聪明 ➔ 聪明的/敏捷的 ➔ adj. 聪明的;敏捷的",
    "smell": "源自散发气味 ➔ 闻到/气味 ➔ v. 闻到 n. 气味",
    "smile": "源自微笑面容 ➔ 微笑 ➔ v./n. 微笑",
    "smoke": "源自烟雾吸烟 ➔ 烟/吸烟 ➔ n. 烟 v. 吸烟;冒烟",
    "smooth": "源自平滑顺畅 ➔ 平滑的/顺利的 ➔ adj. 平滑的;顺利的 v. 使平滑",
    "snake": "源自爬行蛇类 ➔ 蛇 ➔ n. 蛇",
    "snow": "源自降雪 ➔ 雪/下雪 ➔ n. 雪 v. 下雪",
    "so": "源自如此这样 ➔ 如此/所以 ➔ adv. 如此 conj. 所以",
    "soap": "源自洗涤肥皂 ➔ 肥皂 ➔ n. 肥皂",
    "social": "soci (同伴/社会) + -al ➔ 社会的/社交的 ➔ adj. 社会的;社交的",
    "society": "soci (同伴/社会) + -ety ➔ 人类文明社会 ➔ n. 社会;社团",
    "soft": "源自柔和柔软 ➔ 柔软的/柔和的 ➔ adj. 柔软的;柔和的",
    "software": "soft (软) + ware (物件) ➔ 计算机软件 ➔ n. 软件",
    "soil": "sol (泥土/地面) ➔ 土壤/泥土 ➔ n. 土壤;泥土",
    "solar": "sol (太阳) + -ar ➔ 太阳的/日光的 ➔ adj. 太阳的;日光的",
    "soldier": "solidus (古金币/拿薪水的士兵) ➔ 士兵 ➔ n. 士兵;军人",
    "solid": "sol (完整/坚固) + -id ➔ 固体的/坚固的 ➔ adj. 固体的;坚固的 n. 固体",
    "solution": "solve (解决) + -ution ➔ 解决方案/溶液 ➔ n. 解决方案;溶液",
    "solve": "solve (解开) ➔ 解决/解答 ➔ v. 解决;解答",
    "some": "源自某些若干 ➔ 一些/某些 ➔ adj./pron. 一些;某些",
    "somebody": "some (某) + body (人) ➔ 某人 ➔ pron. 某人;重要人物",
    "somehow": "some (某) + how (方式) ➔ 以某种方式/不知怎么地 ➔ adv. 以某种方式",
    "someone": "some (某) + one (人) ➔ 某人 ➔ pron. 某人",
    "something": "some (某) + thing (事) ➔ 某事/某物 ➔ pron. 某事;某物",
    "sometimes": "some (某些) + times (时间) ➔ 有时/时不时 ➔ adv. 有时",
    "somewhat": "some (某) + what (什么) ➔ 稍微/有点 ➔ adv. 稍微;有点",
    "somewhere": "some (某) + where (地点) ➔ 在某处 ➔ adv. 在某处",
    "son": "源自儿子 ➔ 儿子 ➔ n. 儿子",
    "song": "sing (唱歌) ➔ 歌曲 ➔ n. 歌曲",
    "soon": "源自立刻很快 ➔ 很快/不久 ➔ adv. 不久;很快",
    "sorrow": "sore (痛) + -ow ➔ 悲伤/痛心 ➔ n. 悲伤;悲痛",
    "sorry": "sore (难过痛心) + -y ➔ 报歉难过的 ➔ adj. 抱歉的;难过的",
    "sort": "sort (种类/挑选) ➔ 种类/分类 ➔ n. 种类 v. 分类",
    "soul": "源自灵魂心灵 ➔ 灵魂/心灵 ➔ n. 灵魂;心灵",
    "sound": "源自声音发声 ➔ 声音/听起来 ➔ n. 声音 v. 听起来 adj. 健康安全的",
    "soup": "源自浓汤羹 ➔ 汤 ➔ n. 汤",
    "source": "sur (升起) + -ce ➔ 涌出水源的源头 ➔ n. 源头;来源",
    "south": "源自太阳照耀的南方 ➔ 南方 ➔ n. 南方 adj. 南方的",
    "southern": "south (南方) + -ern ➔ 南方的 ➔ adj. 南方的",
    "space": "spat (空间) ➔ 空间/太空 ➔ n. 空间;太空",
    "spacious": "space (空间) + -ious ➔ 宽敞的 ➔ adj. 宽敞的",
    "spare": "源自节约节省 ➔ 备用的/抽出时间 ➔ adj. 备用的 v. 抽出",
    "speak": "源自开口说话 ➔ 说话/演讲 ➔ v. 说话;演讲",
    "speaker": "speak (说话) + -er (人/物) ➔ 演讲者/扬声器 ➔ n. 演讲者;扬声器",
    "special": "spec (外观/种类) + -ial ➔ 独具一格特殊的 ➔ adj. 特殊的;特别的",
    "specialist": "special (专门) + -ist (人) ➔ 专家 ➔ n. 专家;专科医生",
    "specialize": "special (专门) + -ize ➔ 专门从事 ➔ v. 专攻;专门从事",
    "species": "spec (外观/种类) ➔ 生物物种 ➔ n. 物种;种类",
    "specific": "spec (特定) + fic (做) ➔ 明确具体的 ➔ adj. 具体的;特定的",
    "speech": "speak (说话) ➔ 演讲/言语 ➔ n. 演讲;言语",
    "speed": "源自繁荣/速度 ➔ 速度/加速 ➔ n. 速度 v. 加速",
    "spell": "源自拼写字词 ➔ 拼写 ➔ v. 拼写 n. 符咒",
    "spill": "源自泼洒流出 ➔ 溢出/泼洒 ➔ v. 溢出;泼洒",
    "spin": "源自纺线旋转 ➔ 旋转 ➔ v./n. 旋转;纺纱",
    "spirit": "spir (呼吸/心灵) + -it ➔ 精神/灵魂 ➔ n. 精神;灵魂;气概",
    "spite": "despite (轻视) ➔ 怨恨/恶意 ➔ n. 恶意;怨恨",
    "splendid": "splend (发光/辉煌) + -id ➔ 辉煌极好的 ➔ adj. 极好的;辉煌的",
    "split": "源自裂开劈开 ➔ 劈开/分裂 ➔ v./n. 劈开;分裂",
    "spoil": "源自掠夺/损坏 ➔ 破坏/溺爱 ➔ v. 破坏;溺爱;变质",
    "sponsor": "spon (承诺/赞助) + -or ➔ 出资赞助的机构 ➔ n. 赞助商 v. 赞助",
    "spoon": "源自木片勺子 ➔ 勺子 ➔ n. 勺子",
    "sport": "disport (消遣娱乐) ➔ 体育运动 ➔ n. 体育运动",
    "spread": "源自伸展铺开 ➔ 传播/蔓延 ➔ v./n. 传播;蔓延;铺开",
    "spring": "源自喷涌/弹跳 ➔ 春天/泉水/弹簧 ➔ n. 春天;泉水;弹簧 v. 跳跃",
    "square": "quadr (四) + -ate ➔ 正方形/广场 ➔ n. 正方形;广场 adj. 正方形的",
    "stability": "stable (稳定) + -ity ➔ 稳定性 ➔ n. 稳定性",
    "stable": "st (站立) + -able ➔ 站立稳固不摇晃的 ➔ adj. 稳定的 n. 马厩",
    "stadium": "stad (露天竞技场) + -ium ➔ 体育场 ➔ n. 体育场",
    "staff": "源自支撑木棍/全员 ➔ 全体工作人员 ➔ n. 全体职工 v. 配备人员",
    "stage": "st (站立) + -age ➔ 舞台/阶段 ➔ n. 舞台;阶段 v. 上演",
    "stair": "源自踏步阶梯 ➔ 楼梯 ➔ n. 楼梯",
    "stamp": "源自重踩印记 ➔ 邮票/印章 ➔ n. 邮票;印章 v. 盖印;跺脚",
    "stand": "st (站立) + -and ➔ 站立/忍受 ➔ v. 站立;忍受 n. 看台;摊位",
    "standard": "stand (站立) + hard (坚固) ➔ 竖立起的标准 ➔ n. 标准 adj. 标准的",
    "star": "源自夜空星辰 ➔ 星星/明星 ➔ n. 星星;明星 v. 主演",
    "stare": "源自凝视僵视 ➔ 凝视/盯着看 ➔ v./n. 凝视;盯着看",
    "start": "源自跳跃冲刺 ➔ 开始/启动 ➔ v./n. 开始;启动",
    "state": "st (站立/状态) + -e ➔ 状态/国家/陈述 ➔ n. 状态;国家 v. 声明;陈述",
    "statement": "state (陈述) + -ment ➔ 发布的声明 ➔ n. 声明;陈述",
    "station": "st (站立) + -ion ➔ 停靠站/车站 ➔ n. 车站;局;台",
    "statistic": "state (国家统计) + -istic ➔ 统计数据 ➔ n. 统计数值",
    "statue": "st (站立) + -ue ➔ 塑像/雕像 ➔ n. 雕像;塑像",
    "status": "st (站立/身份) + -us ➔ 地位/状态 ➔ n. 身份;地位;状态",
    "stay": "st (站立/停留) + -ay ➔ 停留/保持 ➔ v. 停留;保持 n. 逗留",
    "steady": "stead (站立) + -y ➔ 平稳持续的 ➔ adj. 平稳的 v. 使稳定",
    "steal": "源自偷窃盗取 ➔ 偷窃 ➔ v. 偷窃",
    "steam": "源自水蒸气 ➔ 蒸汽/水汽 ➔ n. 蒸汽 v. 蒸发;蒸",
    "steel": "源自坚硬钢铁 ➔ 钢铁 ➔ n. 钢铁",
    "steep": "源自陡峭险峻 ➔ 陡峭的 ➔ adj. 陡峭的;急剧的",
    "steer": "源自驾驶操纵 ➔ 操纵/驾驶 ➔ v. 驾驶;引导",
    "stem": "源自主干茎叶 ➔ 茎/干/源于 ➔ n. 茎;干 v. 源于",
    "step": "源自迈步踏步 ➔ 步骤/脚步 ➔ n. 步骤;脚步 v. 迈步",
    "stick": "源自刺/木棍 ➔ 木棍/粘贴 ➔ n. 木棍 v. 粘贴;刺",
    "stiff": "源自僵硬死板 ➔ 僵硬的/硬挺的 ➔ adj. 僵硬的;硬挺的",
    "still": "st (站立/静止) + -ill ➔ 静止的/仍然 ➔ adj. 静止的 adv. 仍然",
    "stimulate": "stimul (刺/激发) + -ate ➔ 刺激激发 ➔ v. 刺激;激发",
    "stimulus": "stimul (刺/激发) + -us ➔ 刺激物 ➔ n. 刺激;刺激物",
    "stir": "源自搅动扰动 ➔ 搅拌/搅动 ➔ v./n. 搅拌;搅动",
    "stock": "源自树干储备 ➔ 库存/股票 ➔ n. 库存;股票;存货",
    "stomach": "stom (入口/胃) + -ach ➔ 胃/肚子 ➔ n. 胃;肚子",
    "stone": "源自石头坚硬 ➔ 石头 ➔ n. 石头",
    "stop": "源自塞住停止 ➔ 停止/车站 ➔ v. 停止 n. 车站;停止",
    "storage": "store (储藏) + -age ➔ 存储/储藏 ➔ n. 存储;库房",
    "store": "instaur (储备/建) ➔ 商店/储藏 ➔ n. 商店;储备 v. 储藏",
    "storm": "源自风暴雷雨 ➔ 暴风雨 ➔ n. 暴风雨 v. 猛攻",
    "story": "histor (历史故事) ➔ 故事/小说 ➔ n. 故事;小说",
    "stove": "源自火炉炉子 ➔ 炉子 ➔ n. 炉子;火炉",
    "straight": "stretch (拉直) ➔ 直的/直接 ➔ adj. 直的 adv. 直接地",
    "strange": "extraneus (外来的) ➔ 奇怪不熟悉的 ➔ adj. 奇怪的;陌生的",
    "stranger": "strange (陌生) + -er (人) ➔ 陌生人 ➔ n. 陌生人",
    "strategy": "strat (军队/将军) + egy (引导) ➔ 战略/策略 ➔ n. 战略;策略",
    "straw": "源自铺垫干草 ➔ 稻草/吸管 ➔ n. 稻草;吸管",
    "stream": "源自水流溪流 ➔ 溪流/流动 ➔ n. 溪流;水流 v. 流动",
    "street": "strata (铺石道路) ➔ 街道 ➔ n. 街道",
    "strength": "strong (强壮) + -th ➔ 力量/实力 ➔ n. 力量;实力",
    "strengthen": "strength (力量) + -en (使) ➔ 加强/巩固 ➔ v. 加强;巩固",
    "stress": "strict (拉紧/压力) ➔ 压力/强调 ➔ n. 压力;重音 v. 强调",
    "stretch": "源自拉伸延伸 ➔ 伸展/延伸 ➔ v./n. 伸展;延伸",
    "strict": "strict (拉紧/严格) ➔ 严格的/严厉的 ➔ adj. 严格的;严厉的",
    "strike": "源自打击击打 ➔ 打击/罢工 ➔ v./n. 打击;罢工;袭击",
    "string": "源自细绳线条 ➔ 细绳/一串 ➔ n. 细绳;一串",
    "strip": "源自剥去长条 ➔ 剥去/长条 ➔ v. 剥去 n. 长条",
    "strive": "源自奋斗争夺 ➔ 奋斗/努力 ➔ v. 努力;奋斗",
    "stroke": "strike (打击) + -e ➔ 中风/笔画/击打 ➔ n. 中风;笔画;击打",
    "strong": "源自强壮结实 ➔ 强壮的/强烈的 ➔ adj. 强壮的;强烈的",
    "structural": "structure (结构) + -al ➔ 结构的 ➔ adj. 结构的",
    "structure": "struct (建造) + -ure ➔ 结构/建筑物 ➔ n. 结构;建筑物",
    "struggle": "源自挣扎奋斗 ➔ 奋斗/挣扎 ➔ v./n. 挣扎;奋斗",
    "student": "stud (热心/学习) + -ent (人) ➔ 学生 ➔ n. 学生",
    "studio": "stud (学习/研究室) ➔ 工作室/画室 ➔ n. 工作室;录音室",
    "study": "stud (热心追求知识) ➔ 学习/研究 ➔ v./n. 学习;研究;书房",
    "stuff": "源自材料充填 ➔ 材料/东西 ➔ n. 东西;材料 v. 塞满",
    "stupid": "stup (愣住/愚蠢) + -id ➔ 愚蠢傻的 ➔ adj. 愚蠢的",
    "style": "styl (刻字笔/风格) ➔ 风格/样式 ➔ n. 风格;样式",
    "subject": "sub- (在下) + ject (投掷) ➔ 主题/科目/受制于 ➔ n. 主题;科目 adj. 受制于",
    "subjective": "subject (主观) + -ive ➔ 主观的 ➔ adj. 主观的",
    "submit": "sub- (在下) + mit (递交) ➔ 提交/屈服 ➔ v. 提交;屈服",
    "subsequent": "sub- (在后) + sequ (跟随) + -ent ➔ 随后的 ➔ adj. 随后的",
    "substance": "sub- (在下) + stance (站立) ➔ 支撑底层的物质 ➔ n. 物质;实质",
    "substantial": "substance (实质/大量) + -ial ➔ 大量的/切实的 ➔ adj. 大量的;切实的",
    "substitute": "sub- (在下) + stit (代替) + -ute ➔ 替代/替代品 ➔ v. 替代 n. 替代品",
    "subtle": "sub- (微小) + tel (织) ➔ 微妙的/细微的 ➔ adj. 微妙的;细微的",
    "suburb": "sub- (靠近) + urb (城市) ➔ 郊区 ➔ n. 郊区",
    "succeed": "sub- (在后) + ceed (走) ➔ 顺着走下去成功 ➔ v. 成功;继承",
    "success": "succeed (成功) + -ss ➔ 成功 ➔ n. 成功",
    "successful": "success (成功) + -ful ➔ 成功的 ➔ adj. 成功的",
    "succession": "succeed (接替) + -sion ➔ 连续/继承 ➔ n. 连续;继承",
    "successive": "succeed (接连) + -ive ➔ 连续的 ➔ adj. 连续的",
    "such": "so (这样) + like (像) ➔ 这样的 ➔ adj./pron. 这样的",
    "suck": "源自吮吸吸入 ➔ 吸/吮 ➔ v. 吮吸",
    "sudden": "sub- (隐秘) + it (走) ➔ 突然发生的 ➔ adj. 突然的",
    "suffer": "sub- (在下) + fer (承受) ➔ 遭受/忍受 ➔ v. 遭受;忍受;受苦",
    "sufficient": "sub- (在下) + fic (做/满足) + -ient ➔ 充分足够的 ➔ adj. 足够的;充分的",
    "sugar": "源自甘蔗糖 ➔ 糖 ➔ n. 糖",
    "suggest": "sub- (在下) + gest (带来/提议) ➔ 建议/暗示 ➔ v. 建议;暗示",
    "suggestion": "suggest (建议) + -ion ➔ 建议/提议 ➔ n. 建议;提议",
    "suit": "sequ (跟随/适合) ➔ 西装/适合 ➔ n. 西装;套装 v. 适合",
    "suitable": "suit (适合) + -able ➔ 合适的 ➔ adj. 合适的;适宜的",
    "sum": "sum (最高/总和) ➔ 总和/金额 ➔ n. 总和;金额 v. 总结",
    "summarize": "summary (总结) + -ize ➔ 概括总结 ➔ v. 总结;概括",
    "summary": "sum (总和) + -ary ➔ 摘要/总结 ➔ n. 摘要;总结",
    "summer": "源自夏季炎热 ➔ 夏天 ➔ n. 夏天;夏季",
    "sun": "源自太阳日照 ➔ 太阳 ➔ n. 太阳",
    "superb": "super (超越) + -b ➔ 极好的/卓越的 ➔ adj. 极好的;卓越的",
    "superior": "super (高于) + -ior ➔ 卓越的高级的 ➔ adj. 卓越的 n. 上级",
    "supermarket": "super (超级) + market (市场) ➔ 超市 ➔ n. 超级市场",
    "supervise": "super- (在上面) + vis (看) ➔ 居高临下监督 ➔ v. 监督;管理",
    "supervisor": "supervise (监督) + -or ➔ 主管/监督员 ➔ n. 主管;监督员",
    "supper": "sup (吮吸/晚餐) ➔ 晚餐 ➔ n. 晚餐",
    "supplement": "sub- (在下) + ple (填满) + -ment ➔ 补充物 ➔ n./v. 补充",
    "supply": "sub- (在下) + ply (填满) ➔ 供给/供应 ➔ v./n. 供应;供给",
    "support": "sub- (在下) + port (支撑) ➔ 底层支撑/支持 ➔ v./n. 支持;支撑",
    "suppose": "sub- (在下) + pose (放置) ➔ 假定/猜想 ➔ v. 假定;猜想",
    "suppress": "sub- (在下) + press (压) ➔ 强行压制/镇压 ➔ v. 压制;镇压",
    "supreme": "super (最高) + -eme ➔ 至高无上的 ➔ adj. 至高无上的;最高的",
    "sure": "se- (离开) + cur (忧虑) ➔ 确信安全的 ➔ adj. 确信的;肯定的",
    "surface": "sur- (表面) + face (脸/面) ➔ 表面/地面 ➔ n. 表面;地面",
    "surgeon": "cheir (手) + erg (工作) ➔ 动外科手术的医生 ➔ n. 外科医生",
    "surgery": "surgeon (外科) + -y ➔ 外科手术 ➔ n. 外科手术;诊所",
    "surpass": "sur- (超越) + pass (经过) ➔ 胜过/超越 ➔ v. 超越;胜过",
    "surplus": "sur- (超出) + plus (加) ➔ 剩余过剩 ➔ n. 剩余 adj. 过剩的",
    "surprise": "sur- (在上面) + pris (抓住) ➔ 突如其来使惊奇 ➔ v. 使惊奇 n. 惊奇",
    "surrender": "sur- (在下) + render (交付) ➔ 投降/交出 ➔ v./n. 投降;放弃",
    "surround": "sur- (在四周) + und (水波) ➔ 包围/环绕 ➔ v. 包围;环绕",
    "survey": "sur- (在上面) + vey (看) ➔ 全面勘测调查 ➔ v./n. 调查;勘测",
    "survival": "survive (生存) + -al ➔ 生存/幸存 ➔ n. 生存;幸存",
    "survive": "sur- (超越) + viv (生命) ➔ 挺过灾难幸存 ➔ v. 幸存;活下来",
    "suspect": "sub- (在下) + spect (看) ➔ 从底下怀疑 ➔ v. 怀疑 n. 嫌疑人",
    "suspend": "sub- (在下) + pend (悬挂) ➔ 暂停/悬挂 ➔ v. 暂停;悬挂",
    "suspicion": "suspect (怀疑) + -ion ➔ 怀疑/猜疑 ➔ n. 怀疑;猜疑",
    "sustain": "sub- (在下) + tain (支撑) ➔ 维持/支撑 ➔ v. 维持;支撑",
    "sustainable": "sustain (可持续) + -able ➔ 可持续的 ➔ adj. 可持续的",
    "swallow": "源自咽下/燕子 ➔ 吞下/燕子 ➔ v. 吞下 n. 燕子",
    "swear": "源自发誓宣誓 ➔ 发誓 ➔ v. 发誓;咒骂",
    "sweat": "源自流汗汗水 ➔ 汗/流汗 ➔ n. 汗 v. 出汗",
    "sweep": "源自扫除打扫 ➔ 扫除 ➔ v. 打扫;席卷",
    "sweet": "源自甜美可口 ➔ 甜的/讨人喜欢的 ➔ adj. 甜的;讨人喜欢的",
    "swift": "源自快速敏捷 ➔ 迅速敏捷的 ➔ adj. 迅速的;敏捷的",
    "swim": "源自游泳戏水 ➔ 游泳 ➔ v./n. 游泳",
    "swing": "源自摆动摇摆 ➔ 摇摆/秋千 ➔ v./n. 摇摆;秋千",
    "symbol": "sym- (共同) + bol (投掷) ➔ 代表某种象征符号 ➔ n. 符号;象征",
    "sympathy": "sym- (共同) + path (感受) ➔ 感同身受的同情 ➔ n. 同情;共鸣",
    "symptom": "sym- (共同) + ptom (落下) ➔ 病症显现的症状 ➔ n. 症状;征兆",
    "system": "syn- (共同) + st (站立) ➔ 站立在一起构成的体系 ➔ n. 系统;体系;制度",
    "systematic": "system (系统) + -atic ➔ 系统有条理的 ➔ adj. 系统的;有条理的"
}

def apply_deep_etymology():
    with open('target_words_data.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    updated_count = 0
    cleaned_count = 0
    
    for item in data:
        w_lower = item['word'].lower().strip()
        meaning = item['meaning']
        phrase = item.get('phrase', '')
        
        # Priority 1: Exact meaningful etymology from dictionary
        if w_lower in ETEMY_DICTIONARY:
            item['etymology'] = ETEMY_DICTIONARY[w_lower]
            updated_count += 1
        else:
            # Priority 2: Sanitize bad mechanical string substractions like 're- + frigerator'
            curr_etym = item.get('etymology', '')
            if '表示动作重复' in curr_etym or '表达相反否定' in curr_etym or '表示方向朝向' in curr_etym or '+' in curr_etym:
                # Replace with clean, meaningful memory hook
                item['etymology'] = f"【核心高频词】: {item['word']} ➔ 搭配助记: 【{phrase}】 ➔ {meaning}"
                cleaned_count += 1
                
    with open('target_words_data.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        
    print(f"Applied deep dictionary etymologies to {updated_count} words.")
    print(f"Sanitized mechanical template fallbacks for {cleaned_count} words.")

if __name__ == '__main__':
    apply_deep_etymology()
