import json, re

# Comprehensive root and affix dictionary for自考 English words
PREFIXES = [
    ('anti', 'anti- (反对/抗)', '表达对抗或相反作用'),
    ('trans', 'trans- (跨越/转变)', '表示跨越、转移或改变状态'),
    ('inter', 'inter- (在……之间/相互)', '表示两者之间的相互作用'),
    ('super', 'super- (超过/超级)', '表示超越或在上方'),
    ('under', 'under- (在……下方/不足)', '表示处于下方或程度不够'),
    ('over', 'over- (过度/在……上方)', '表示超出限度或覆盖在上方'),
    ('fore', 'fore- (前/预先)', '表示位置靠前或时间提前'),
    ('post', 'post- (后/在……之后)', '表示时间或位置靠后'),
    ('sub', 'sub- (在……下方/次级)', '表示处于下层或附属地位'),
    ('pro', 'pro- (向前/赞成/支持)', '表示向前推进或支持'),
    ('pre', 'pre- (在……之前/预先)', '表示提前或预先准备'),
    ('per', 'per- (贯穿/彻底)', '表示贯穿整个过程或完全彻底'),
    ('dis', 'dis- (分开/剥夺/相反)', '表示否定、分离或相反状态'),
    ('mis', 'mis- (错误/坏)', '表示错误的动作或不当状态'),
    ('out', 'out- (胜过/向外)', '表示超越或由内向外'),
    ('non', 'non- (非/不)', '纯粹表达否定含义'),
    ('con', 'con-/com-/col-/cor- (共同/聚拢/加强)', '表示聚集在一起或强烈程度'),
    ('sym', 'sym-/syn- (共同/同步)', '表示同步或协调一致'),
    ('re', 're- (重新/再次/向后)', '表示动作重复或向后反作用'),
    ('un', 'un- (否定/相反/解开)', '表达相反否定或解除状态'),
    ('in', 'in-/im-/ir-/il- (向内/进入 或 否定/无)', '表示进入内部或表达相反否定'),
    ('ex', 'ex-/e- (向外/脱离)', '表示由内向外伸展或脱离'),
    ('ab', 'ab-/abs- (偏离/离去)', '表示脱离或偏离正轨'),
    ('ad', 'ad-/ac-/af-/ag-/ap-/ar-/as-/at- (去/朝向/加强)', '表示方向朝向或动作加强'),
    ('de', 'de- (向下/离开/除去)', '表示向下降低或彻底剥夺'),
    ('en', 'en-/em- (使成为/放入)', '表示使进入某种状态或赋予')
]

SUFFIXES = [
    ('relationship', '-ship (身份/关系后缀)', '表达抽象关系或身份资格'),
    ('ability', '-ability/-ibility (可……性/能力)', '表达具备某种性质的能力'),
    ('ation', '-ation/-tion/-sion (抽象名词后缀)', '表达动作的过程、状态或结果'),
    ('ment', '-ment (名词后缀)', '表达行为的过程、手段或结果'),
    ('ness', '-ness (抽象名词后缀)', '将形容词转为表达性质或状态的名词'),
    ('able', '-able/-ible (形容词: 可……的)', '表达具备某种能力或性质的'),
    ('less', '-less (否定形容词: 无……的)', '表达缺乏、没有某种特征'),
    ('ful', '-ful (形容词: 充满……的)', '表达充满某种性质或特征'),
    ('ive', '-ive (形容词后缀)', '表达具有某种倾向、性质或特征的'),
    ('ous', '-ous/-ious (形容词后缀)', '表达富含某种性质或特征的'),
    ('ize', '-ize/-ise (动词: 使……化)', '表达使变成某种状态或实现某种目的'),
    ('ify', '-ify (动词: 使……化)', '表达使变成某种性质或特定状态'),
    ('ist', '-ist (名词: 专业人员/学者)', '表达从事某专业领域的人'),
    ('or', '-or/-er (名词: 做……的人/物)', '表达执行某动作的人或工具器具'),
    ('ly', '-ly (副词/形容词后缀)', '表达方式、状态或频率'),
    ('al', '-al (形容词/名词后缀)', '表达与……相关的或某种行为过程')
]

CUSTOM_ETYMOLOGY = {
    "instead": "in- (在内) + stead (位置/地方) ➔ 占据他人的位置 ➔ adv. 代替;反而",
    "institute": "in- (在内) + stit (站立/设立) + -ute ➔ 设立在内部的机构 ➔ v.建立 n.机构",
    "interest": "inter- (在……中间) + est (存在) ➔ 存在于两者之间的切身利益 ➔ n.兴趣;利益;利息",
    "invite": "in- (向内) + vite (呼唤/召集) ➔ 呼唤请人进入室内 ➔ v.邀请;招致",
    "island": "is- (水/岛) + land (陆地) ➔ 环绕水中的陆地 ➔ n.岛",
    "item": "拉丁语 item (同样地/项目) ➔ 逐项列出的条目 ➔ n.项目;商品;一则",
    "absorb": "ab- (离去/吸收) + sorb (吞咽) ➔ 彻底吞吸进去 ➔ v.吸收;吸引",
    "abstract": "abs- (离去) + tract (拉) ➔ 从具体事物中抽取出来的概念 ➔ adj.抽象的 n.摘要",
    "academic": "Academia (希腊阿卡德米学园) + -ic ➔ 学术相关的 ➔ adj.学术的;学院的",
    "accent": "ac- (去/朝向) + cent (唱歌/发声) ➔ 发音的调子 ➔ n.口音;重音",
    "accept": "ac- (去) + cept (拿/接收) ➔ 伸手接过来 ➔ v.接受;认可",
    "access": "ac- (去) + cess (走) ➔ 走近并进入的通道 ➔ n.通道;入口 v.存取",
    "accident": "ac- (去) + cid (落下/发生) + -ent ➔ 突然掉落发生的突发事件 ➔ n.事故;意外",
    "accomplish": "ac- (加强) + compl (填满) + -ish ➔ 完全做满做好 ➔ v.完成;实现",
    "account": "ac- (去) + count (数/计算) ➔ 记录算账的明细 ➔ n.账户;解释 v.说明",
    "accurate": "ac- (去) + cur (关心/精细) + -ate ➔ 精细照料毫无差错的 ➔ adj.精确的;准确的",
    "achieve": "a- (去) + chiev (头/顶峰) ➔ 走到最高顶峰 ➔ v.取得;实现;达到",
    "acquire": "ac- (去) + quire (寻求/获得) ➔ 寻找并得到 ➔ v.获得;取得;学到",
    "adapt": "ad- (去) + apt (适合) ➔ 使自己去适合环境 ➔ v.适应;改编",
    "addition": "add (加/给予) + -ition (名词后缀) ➔ 增加的部分 ➔ n.加法;增加物",
    "adequate": "ad- (去) + equ (平等/相符) + -ate ➔ 达到相符标准的 ➔ adj.足够的;胜任的",
    "adjust": "ad- (去) + just (正确/公正) ➔ 使调到正确位置 ➔ v.调整;调节;适应",
    "admire": "ad- (去) + mir (惊奇/看) ➔ 带着惊叹去注视 ➔ v.钦佩;赞赏;羡慕",
    "admit": "ad- (去) + mit (准许进入/发送) ➔ 允许进入或承认事实 ➔ v.承认;准许进入",
    "adopt": "ad- (去) + opt (选择) ➔ 做出选择并收纳 ➔ v.采用;收养;采纳",
    "advance": "ab- (向前) + ance (名词) ➔ 前进推近 ➔ v./n.前进;提升;预先",
    "advantage": "advance (向前) + -age (名词) ➔ 处于前方有利位置 ➔ n.优势;有利条件",
    "adventure": "ad- (去) + vent (来/发生) + -ure ➔ 即将来临的未知考验 ➔ n.冒险;奇遇",
    "advertise": "ad- (去) + vert (转动) + -ise ➔ 把大众注意力吸引转过来 ➔ v.做广告;宣传",
    "advice": "ad- (去) + vic (看/见解) ➔ 给予见解指导 ➔ n.建议;忠告",
    "advocate": "ad- (去) + voc (声音/呼喊) + -ate ➔ 大声呼吁发声支持 ➔ v.提倡;主张 n.拥护者",
    "affair": "af- (去) + fair (做/事务) ➔ 必须去做的事情 ➔ n.事务;事件;私情",
    "affect": "af- (去) + fect (做/作用) ➔ 作用于某物产生改变 ➔ v.影响;感动",
    "afford": "af- (去) + forth (向前) ➔ 能向前支付得出费用 ➔ v.买得起;承担得起",
    "agency": "ag (做/驱动) + -ency (机构) ➔ 代为执行事务的机构 ➔ n.代理机构;中介",
    "aggressive": "ag- (去) + gress (行走/迈步) + -ive ➔ 步步紧逼挑衅的 ➔ adj.好斗的;侵略性的",
    "agree": "a- (去) + gree (高兴/满意) ➔ 双方都感到满意 ➔ v.同意;赞同",
    "agriculture": "agri (田地) + culture (耕作/培养) ➔ 田地耕作技术 ➔ n.农业;农艺",
    "alarm": "all (全部) + arme (武器) ➔ 喊大家拿起武器警戒 ➔ n.警报;闹钟 v.使惊恐",
    "alcohol": "阿拉伯语 al-kuhl (精细粉末/蒸馏精) ➔ 蒸馏出的酒精 ➔ n.酒精;乙醇",
    "allow": "al- (去) + low (赞许/承认) ➔ 给予认可准许 ➔ v.允许;准许;考虑",
    "amend": "a- (去) + mend (缺陷/错误) ➔ 除去错误缺陷 ➔ v.修改;修正;改进",
    "analyze": "ana- (解开/拆分) + lyze (溶解) ➔ 拆解开来进行深入剖析 ➔ v.分析;分解",
    "ancient": "ante (在……之前) + -ient ➔ 久远以前年代的 ➔ adj.古代的;古老的",
    "announce": "an- (去) + nounce (宣告/讲述) ➔ 向公众发布消息 ➔ v.宣布;通告",
    "annoy": "in (使) + odi (讨厌) ➔ 使人感到烦躁厌恶 ➔ v.打扰;使恼怒",
    "annual": "ann (年) + -ual (形容词) ➔ 每年发生一次的 ➔ adj.每年的;年度的",
    "apology": "apo- (离开/远) + log (言语/解释) ➔ 为解开误会而说的解释致歉 ➔ n.道歉;认错",
    "apparent": "ap- (去) + par (出现/显现) + -ent ➔ 显现出来一目了然的 ➔ adj.明显的;显而易见的",
    "appeal": "ap- (去) + peal (推/呼唤) ➔ 向高层或大众呼吁求助 ➔ v./n.呼吁;上诉;吸引",
    "appear": "ap- (去) + par (显现) ➔ 出现展示在面前 ➔ v.出现;显得;好像",
    "applicant": "ap- (去) + plic (折叠/提交) + -ant ➔ 递交申请表的人 ➔ n.申请人",
    "application": "apply (申请/应用) + -ation ➔ 提出申请或具体应用 ➔ n.申请;应用;应用程序",
    "appoint": "ap- (去) + point (指定/点) ➔ 用手指点指定职位 ➔ v.任命;委派;约定",
    "appreciate": "ap- (去) + preci (价值/价格) + -ate ➔ 认可其价值并表达感激 ➔ v.欣赏;感激;领会",
    "approach": "ap- (去) + proach (靠近) ➔ 逐步向目标靠近 ➔ v./n.靠近;方法;途径",
    "approve": "ap- (去) + prove (证实/赞同) ➔ 证实合格并予以赞同 ➔ v.批准;赞成",
    "argument": "argu (澄清/辩明) + -ment ➔ 互相阐明见解辩论 ➔ n.争论;论点;论据",
    "arrange": "ar- (去) + range (排列/圈) ➔ 把物品排成整齐序列 ➔ v.安排;排列;整理",
    "arrest": "ar- (去) + rest (停止/停留) ➔ 使嫌疑人停止行动扣留 ➔ v./n.逮捕;拘留",
    "arrive": "ar- (去) + riv (岸边) ➔ 靠岸到达目的地 ➔ v.到达;到来",
    "artificial": "arti (技巧/人工) + fic (做) + -ial ➔ 人工用技巧做出的 ➔ adj.人造的;人工的",
    "artist": "art (艺术) + -ist (人) ➔ 从事艺术创作的人 ➔ n.艺术家;画家",
    "ashamed": "a- (处于) + shame (羞耻) + -ed ➔ 感到羞愧难当的 ➔ adj.惭愧的;羞耻的",
    "aspect": "a- (去) + spect (看) ➔ 从某个特定视角去看 ➔ n.方面;外观;外表",
    "assess": "as- (去) + sess (坐/评估) ➔ 坐在评估员位置进行考量 ➔ v.评估;估算;评定",
    "assign": "as- (去) + sign (标记/签名) ➔ 签名单独指定任务 ➔ v.分配;指派;布置",
    "assist": "as- (去) + sist (站立) ➔ 站在旁边伸出援手 ➔ v.帮助;协助;援助",
    "associate": "as- (去) + soci (同伴/结交) + -ate ➔ 结为同伴产生联系 ➔ v.联想;关联 n.伙伴",
    "assume": "as- (去) + sume (拿/取) ➔ 先自行拿定主意假设 ➔ v.假定;承担;设想",
    "assure": "as- (去) + sure (确信) ➔ 使对方心里确信无疑 ➔ v.向……保证;使确信",
    "astonish": "a- (去) + ton (雷声) + -ish ➔ 像被雷声震慑住一样震惊 ➔ v.使惊恐;使吃惊",
    "athlete": "athl (比赛/奖品) + -ete (人) ➔ 参加体育竞技的人 ➔ n.运动员",
    "attached": "at- (去) + tach (钉子/连接) + -ed ➔ 被固定连接在一起的 ➔ adj.附加的;依恋的",
    "attempt": "at- (去) + tempt (尝试/试探) ➔ 努力去试一试 ➔ v./n.尝试;企图",
    "attend": "at- (去) + tend (伸展/前往) ➔ 把精力伸向现场出席 ➔ v.出席;参加;照顾",
    "attention": "at- (去) + tent (伸) + -ion ➔ 把耳朵和心思伸过去倾听 ➔ n.注意;专心",
    "attitude": "atti (姿态/适合) + -tude (状态) ➔ 看待事物的身体与心理姿态 ➔ n.态度;看法",
    "attract": "at- (去) + tract (拉/吸引) ➔ 把目光和注意力拉过来 ➔ v.吸引;引起",
    "attribute": "at- (去) + tribute (给予/归因) ➔ 把原因归于某事物 ➔ v.归因于 n.属性;特征",
    "audience": "audi (听) + -ence (人群) ➔ 坐在现场倾听的人群 ➔ n.听众;观众",
    "authentic": "authent (自己做/亲手) + -ic ➔ 亲手做真实的 ➔ adj.真实的;地道的;真迹的",
    "authority": "author (创造者/源头) + -ity ➔ 拥有决定权和指挥权 ➔ n.权威;官方;权力",
    "automatic": "auto- (自动) + mat (思考/意愿) + -ic ➔ 依靠机器自身运转的 ➔ adj.自动的;无意识的",
    "available": "a- (去) + vail (价值/有用) + -able ➔ 可派上用场可获取的 ➔ adj.可获得的;有空的",
    "average": "haverie (海损平摊) ➔ 大家共同平摊的分额 ➔ n./adj.平均数;平均的",
    "avoid": "a- (去) + void (空/离开) ➔ 使自己清空避开风险 ➔ v.避免;避开;逃避",
    "aware": "a- (处于) + ware (警觉) ➔ 处于警觉警醒状态 ➔ adj.意识到的;察觉到的",
    "barrier": "bar (栏杆/障碍) + -ier ➔ 阻挡前行的栅栏 ➔ n.障碍;屏障;关卡",
    "behavior": "be- (关于) + have (持有/表现) + -ior ➔ 外在表现出来的举止 ➔ n.行为;举止",
    "belief": "be- (使) + lief (喜爱/信任) ➔ 内心深处坚信不疑 ➔ n.信念;信任;信仰",
    "beneficial": "bene (好) + fic (做) + -ial ➔ 做了好事带来益处的 ➔ adj.有益的;有利的",
    "benefit": "bene (好) + fit (做) ➔ 带来的好结果 ➔ n.利益;好处 v.受益",
    "boundary": "bound (界限/边界) + -ary ➔ 划分区域的分界线 ➔ n.边界;分界线",
    "budget": "bougette (小皮袋) ➔ 装钱的小算盘袋子 ➔ n.预算 v.编制预算",
    "burden": "bear (承受/担负) + -den ➔ 背负在身上的重担 ➔ n.负担;重担 v.加重负担",
    "calculate": "calculus (小石头/算盘子) + -ate ➔ 用小石子摆盘计算 ➔ v.计算;核算;推算",
    "candidate": "candidus (穿白袍者) + -ate ➔ 罗马时期穿白袍竞选的人 ➔ n.候选人;应试者",
    "capacity": "cap (拿/容纳) + -acity ➔ 能够拿取容纳的最大量 ➔ n.容量;能力;性能",
    "capital": "capit (头/首要) + -al ➔ 首要城市或主干资金 ➔ n.首都;资本;大写字母",
    "capture": "capt (抓住) + -ure ➔ 动手捉住或捕获 ➔ v.捕获;俘虏;夺取",
    "career": "carr (车/道路) + -eer ➔ 驾车前行的职业生涯路线 ➔ n.职业;生涯",
    "cautious": "caut (小心/警惕) + -ious ➔ 保持高度警惕謹慎的 ➔ adj.谨慎的;小心的",
    "celebrate": "celebr (盛大/名声) + -ate ➔ 举办盛大仪式进行庆祝 ➔ v.庆祝;歌颂",
    "challenge": "calumnia (虚假指控) ➔ 发起质问与挑战 ➔ n./v.挑战;质疑",
    "chamber": "camera (拱顶房间) ➔ 封闭会议室或心室 ➔ n.会议室;腔;室",
    "character": "charac (刻划/印记) + -ter ➔ 刻画在性格上的烙印 ➔ n.性格;角色;汉字",
    "charity": "char (亲爱/仁慈) + -ity ➔ 怀着仁爱之心施舍 ➔ n.慈善机构;慈善;宽容",
    "chemical": "chem (炼金术/化学) + -ical ➔ 与化学物质相关的 ➔ adj.化学的 n.化学品",
    "circumstance": "circum- (周围) + stance (站立) ➔ 站立在四周的环境条件 ➔ n.环境;条件;境况",
    "civil": "civis (公民) + -il ➔ 公民城邦内部的 ➔ adj.公民的;文职的;礼貌的",
    "claim": "claim/clam (呼喊/声称) ➔ 大声呼喊主张权利 ➔ v./n.声称;索赔;断言",
    "clarify": "clar (清楚) + -ify (使) ➔ 使原本模糊的事物变得清晰 ➔ v.澄清;阐明",
    "classic": "class (等级/第一流) + -ic ➔ 达到顶级流传的 ➔ adj.经典的 n.名著",
    "classify": "class (类别) + -ify (使) ➔ 按类别整理归类 ➔ v.分类;归类",
    "climate": "klima (倾斜/纬度) ➔ 太阳倾斜照射形成的气候 ➔ n.气候;风气",
    "climb": "源自攀爬向上 ➔ v.攀登;爬;上升 n.攀登",
    "clinic": "clin (倾斜/卧床) + -ic ➔ 照顾卧床病人的小诊所 ➔ n.诊所;门诊部",
    "cognitive": "cogn (知道/认知) + -itive ➔ 与大脑认知获知相关的 ➔ adj.认知的;感知的",
    "coincidence": "co- (共同) + in- (在内) + cide (落下) + -ence ➔ 巧合落在同一时间点 ➔ n.巧合;一致",
    "collapse": "col- (共同) + lapse (滑落/坍塌) ➔ 一起向内滑落塌陷 ➔ v./n.崩溃;倒塌;虚脱",
    "colleague": "col- (共同) + league (结合/同盟) ➔ 在同一单位共事的人 ➔ n.同事;同僚",
    "collect": "col- (共同) + lect (挑选/收集) ➔ 把分散的物品挑选聚集起来 ➔ v.收集;采集;收缴",
    "combine": "com- (共同) + bi (两个) ➔ 将两者结合绑定在一起 ➔ v.结合;联合;合并",
    "comfort": "com- (加强) + fort (力量/强壮) ➔ 给予精神力量抚慰创伤 ➔ n.舒适;安慰 v.安慰",
    "command": "com- (加强) + mand (命令/委托) ➔ 下达指令强制执行 ➔ v./n.命令;指挥;掌握",
    "comment": "com- (共同) + ment (思考/心智) ➔ 表达内心的想法意见 ➔ n./v.评论;意见;解释",
    "commercial": "com- (共同) + merc (商品/交易) + -ial ➔ 涉及商品买卖交易的 ➔ adj.商业的 n.广告",
    "commit": "com- (加强) + mit (发送/托付) ➔ 托付全心去投入做某事 ➔ v.承诺;犯罪;托付",
    "committee": "commit (托付) + -ee (受托人) ➔ 接受集体委托全权处理的委员会 ➔ n.委员会",
    "community": "com- (共同) + mun (服务/贡献) + -ity ➔ 大家共同生活互相服务的群体 ➔ n.社区;共同体",
    "company": "com- (共同) + pan (面包) + -y ➔ 一起分吃面包的伙伴/公司 ➔ n.公司;陪伴;同伴",
    "compare": "com- (共同) + pare (平等/对比) ➔ 放在一起对比高下 ➔ v.比较;对比;比作",
    "compatible": "com- (共同) + pati (承受/感觉) + -ible ➔ 能和谐相处共存的 ➔ adj.兼容的;和谐的",
    "compensate": "com- (共同) + pens (称重/支付) + -ate ➔ 拿钱去填补称重平衡 ➔ v.补偿;赔偿;弥补",
    "compete": "com- (共同) + pet (追求/奔跑) ➔ 一起追求同一个目标竞争 ➔ v.竞争;比赛",
    "competent": "compete (竞争) + -ent ➔ 在竞争中胜任合格的 ➔ adj.有能力的;胜任的",
    "complain": "com- (加强) + plain (击打/哀悼) ➔ 拍胸发泄心中的不满 ➔ v.抱怨;投诉",
    "compliment": "com- (加强) + pli (填满/致意) + -ment ➔ 礼貌致意表达称赞 ➔ n./v.赞美;恭维;致意",
    "comply": "com- (加强) + ply (折叠/顺从) ➔ 顺从照做不违抗 ➔ v.遵从;服从;顺从",
    "component": "com- (共同) + pon (放置) + -ent ➔ 放在一起组装的零部件 ➔ n.成分;组件;零件",
    "compose": "com- (共同) + pose (放置) ➔ 把各个部分组合放置在一起 ➔ v.组成;创作;使平静",
    "comprehend": "com- (共同) + prehend (抓住) ➔ 在大脑中彻底全面抓住要领 ➔ v.理解;领会;包含",
    "comprehension": "comprehend (理解) + -ion ➔ 大脑全面领会理解能力 ➔ n.理解力;领悟;包含",
    "comprehensive": "comprehend (理解/包含) + -ive ➔ 涵盖包罗万象的 ➔ adj.综合的;全面的;广泛的",
    "compromise": "com- (共同) + promise (承诺) ➔ 双方妥协达成折中让步承诺 ➔ n./v.妥协;让步",
    "conceal": "con- (加强) + ceal (隐藏/盖住) ➔ 彻底盖住掩盖真相 ➔ v.隐藏;隐瞒;遮盖",
    "concede": "con- (加强) + cede (退让/走) ➔ 承认事实退让一步 ➔ v.承认;让步;退让",
    "concentrate": "con- (共同) + centr (中心) + -ate ➔ 全部注意力聚集到中心 ➔ v.集中;聚集;浓缩",
    "concept": "con- (共同) + cept (拿/抓) ➔ 在大脑中构想抓取出的概念 ➔ n.概念;观念;设想",
    "concern": "con- (共同) + cern (筛/关切) ➔ 挂念关切牵动人心 ➔ n.关心;关切;顾虑 v.涉及",
    "conclude": "con- (共同) + clud (关闭) ➔ 事情到此关闭落幕得出结论 ➔ v.推断出;得出结论;结束",
    "conclusion": "conclude (结论) + -ion ➔ 最终的推断与总结 ➔ n.结论;推断;结尾",
    "concrete": "con- (共同) + cret (生长/凝固) + -e ➔ 凝结在一起坚固的 ➔ adj.具体的;混凝土的",
    "condemn": "con- (加强) + demn (伤害/惩罚) ➔ 严厉谴责判罪 ➔ v.谴责;判刑",
    "condition": "con- (共同) + dic (说话/约定) + -ion ➔ 共同商定的前提契约 ➔ n.条件;状况;环境",
    "conduct": "con- (共同) + duct (引导/带领) ➔ 引导组织实施行动 ➔ v.组织;实施;引导 n.行为",
    "confer": "con- (共同) + fer (带来/商讨) ➔ 带来见解共同商议或授予 ➔ v.商讨;授予;协商",
    "conference": "confer (商讨) + -ence (会议) ➔ 专家集中研讨的大会 ➔ n.会议;研讨会",
    "confess": "con- (加强) + fess (说/承认) ➔ 坦白把秘密全部说出 ➔ v.坦白;供认;忏悔",
    "confidence": "con- (加强) + fid (信任) + -ence ➔ 对自己充满完全信任 ➔ n.信心;信任;自信",
    "confident": "con- (加强) + fid (信任) + -ent ➔ 充满信心的 ➔ adj.自信的;确信的",
    "confine": "con- (加强) + fin (界限/限制) ➔ 圈在界限范围内 ➔ v.限制;禁闭 n.界限",
    "confirm": "con- (加强) + firm (坚定/确定) ➔ 再次确认使其坚定无疑 ➔ v.确认;证实;批准",
    "conflict": "con- (共同) + flict (打击) ➔ 互相撞击产生矛盾抵触 ➔ n./v.冲突;矛盾;抵触",
    "conform": "con- (共同) + form (形状/规范) ➔ 保持相同形状规范 ➔ v.符合;遵照;顺应",
    "confront": "con- (共同) + front (前额/正面对抗) ➔ 迎面正面对峙 ➔ v.面对;对抗;正视",
    "confuse": "con- (共同) + fuse (倾倒/混合) ➔ 思想混在一起理不清 ➔ v.使困惑;混淆",
    "congratulate": "con- (共同) + grat (高兴/感谢) + -ulate ➔ 一起表达祝贺高兴 ➔ v.祝贺;恭喜",
    "connect": "con- (共同) + nect (系/绑定) ➔ 把两者拴系相连 ➔ v.连接;关联;沟通",
    "conscious": "con- (共同) + sci (知道) + -ous ➔ 大脑清醒能感知到的 ➔ adj.有意识的;清醒的",
    "consequence": "con- (共同) + sequ (跟随) + -ence ➔ 紧随其后产生的结果 ➔ n.结果;后果;重要性",
    "consequent": "con- (共同) + sequ (跟随) + -ent ➔ 随之发生的 ➔ adj.随之发生的;作为结果的",
    "conservative": "con- (加强) + serv (保存/守住) + -ative ➔ 倾向于保守守旧的 ➔ adj.保守的;守旧的",
    "considerable": "consider (考虑) + -able (值得的) ➔ 值得重视考虑的相当大的 ➔ adj.相当大的;重要的",
    "considerate": "consider (体贴) + -ate ➔ 体贴替他人着想的 ➔ adj.体贴的;周到的",
    "consideration": "consider (考虑) + -ation ➔ 深入考量体贴 ➔ n.考虑;体贴;报酬",
    "consist": "con- (共同) + sist (站立/组成) ➔ 组合站立在一起 ➔ v.由……组成;存在于",
    "consistent": "con- (共同) + sist (站立) + -ent ➔ 始终保持一致立场 ➔ adj.一致的;连续的;连贯的",
    "constant": "con- (加强) + st (站立) + -ant ➔ 坚守站立不变的 ➔ adj.持续的;不断的;恒定的",
    "constitute": "con- (共同) + stit (设立/站立) + -ute ➔ 组合设立构成整体 ➔ v.组成;构成;建立",
    "constitution": "constitute (构成/建立) + -ion ➔ 国家构成的根本大法 ➔ n.宪法;章程;体质",
    "constrain": "con- (加强) + strain (拉紧/束缚) ➔ 紧紧束缚限制 ➔ v.限制;约束;强迫",
    "construct": "con- (共同) + struct (建造) ➔ 将材料建造组装在一起 ➔ v.建造;构筑;创立",
    "consult": "con- (共同) + sult (商讨/跳) ➔ 找专家共同商议咨询 ➔ v.请教;咨询;查阅",
    "consultant": "consult (咨询) + -ant (人) ➔ 提供专业咨询意见的人 ➔ n.顾问;咨询专家",
    "consume": "con- (彻底) + sume (拿/吃掉) ➔ 彻底消耗吃光 ➔ v.消耗;消费;吃完",
    "consumer": "consume (消费) + -er (人) ➔ 进行商品消费的人 ➔ n.消费者;顾客",
    "contain": "con- (共同) + tain (拿住/包含) ➔ 容纳装在里面 ➔ v.包含;容纳;控制",
    "container": "contain (容纳) + -er (器具) ➔ 用来装东西的容器 ➔ n.容器;集装箱",
    "contemporary": "con- (共同) + tempor (时间) + -ary ➔ 处于同一时代的 ➔ adj.当代的;同时代的 n.同时代人",
    "content": "con- (共同) + tent (拿住) ➔ 里面包含的内容或内心满足 ➔ n.内容;目录 adj.满足的",
    "context": "con- (共同) + text (织造/文本) ➔ 编织交织在一起的上下文语境 ➔ n.上下文;语境;背景",
    "continent": "con- (共同) + tin (拿住) + -ent ➔ 紧紧相连的巨大大陆 ➔ n.大陆;洲",
    "continual": "continue (继续) + -al ➔ 频频不断发生的 ➔ adj.频繁的;不断的",
    "continue": "con- (加强) + tinu (持续/保持) ➔ 保持原状不中断 ➔ v.继续;持续;延伸",
    "continuous": "continue (继续) + -ous ➔ 连续不断不间断的 ➔ adj.连续的;持续不断的",
    "contract": "con- (共同) + tract (拉) ➔ 双方拉紧约束在一起的契约 ➔ n.合同;契约 v.收缩;签约",
    "contradict": "contra- (相反) + dict (说话) ➔ 说相反的话打脸 ➔ v.反驳;与……矛盾",
    "contrary": "contra- (相反) + -ary ➔ 朝相反方向的 ➔ adj.相反的 n.反面;相反",
    "contrast": "contra- (相反) + st (站立) ➔ 相对站立形成强烈对比 ➔ n./v.对比;对照",
    "contribute": "con- (共同) + tribute (给予/贡献) ➔ 大家一起奉献力量 ➔ v.贡献;捐献;促成",
    "contribution": "contribute (贡献) + -ion ➔ 奉献出的力量款项 ➔ n.贡献;捐献;稿件",
    "controversial": "contro- (相反) + vers (转/争论) + -ial ➔ 引起多方激烈争论的 ➔ adj.有争议的",
    "convenient": "con- (共同) + ven (来) + -ient ➔ 大家都能方便到来的 ➔ adj.方便的;便利的",
    "convention": "con- (共同) + vent (来/开会) + -ion ➔ 大家聚在一起形成的惯例或大会 ➔ n.大会;惯例;公约",
    "conventional": "convention (惯例) + -al ➔ 遵照传统惯例的 ➔ adj.传统的;惯例的",
    "conversation": "con- (共同) + vers (转动/交流) + -ation ➔ 思想交替碰撞交谈 ➔ n.谈话;交谈",
    "conversely": "con- (相反) + vers (转) + -ely ➔ 朝相反方向转地 ➔ adv.相反地",
    "convert": "con- (彻底) + vert (转动) ➔ 彻底转变形态或信仰 ➔ v.转换;转变;使改变信仰",
    "convey": "con- (共同) + vey (道路/运送) ➔ 沿着道路运送传达消息 ➔ v.传达;运送;表达",
    "convince": "con- (彻底) + vinc (征服/说服) ➔ 彻底征服说服对方 ➔ v.使确信;说服",
    "cooperate": "co- (共同) + oper (工作) + -ate ➔ 共同协作完成工作 ➔ v.合作;协作;配合",
    "coordinate": "co- (共同) + ordin (顺序/协调) + -ate ➔ 协同按顺序排列 ➔ v.协调;整合 adj.同等的",
    "cope": "源自打击/顶住 ➔ 成功应对处理难题 ➔ v.应对;处理;应付",
    "core": "cor (心脏/核心) ➔ 最中心的心脏部位 ➔ n.核心;要点 adj.核心的",
    "corporate": "corpor (身体/社团) + -ate ➔ 结为一体的法人团体 ➔ adj.公司的;团体的",
    "corporation": "corporate (公司) + -ion ➔ 大型企业法人公司 ➔ n.大公司;集团",
    "correct": "cor- (加强) + rect (直/正) ➔ 修正使其完全正确直立 ➔ adj.正确的 v.纠正",
    "correspond": "cor- (共同) + respond (回答/响应) ➔ 互相呼应相符 ➔ v.相符;对应;通信",
    "corrupt": "cor- (彻底) + rupt (打破/破裂) ➔ 彻底腐烂破败 ➔ adj.腐败的 v.使腐化",
    "counsel": "coun- (共同) + sel (召集/商讨) ➔ 集体商议给予劝告 ➔ n.法律顾问;劝告 v.建议",
    "counter": "contra- (相反) ➔ 反方向对抗的柜台 ➔ n.柜台 adv.相反地 v.反驳",
    "courage": "cour (心脏/勇气) + -age ➔ 强大的内心力量 ➔ n.勇气;胆量",
    "create": "cre (生长/创造) + -ate ➔ 从无到有使其生长创造 ➔ v.创造;创建;引起",
    "creation": "create (创造) + -ion ➔ 创造出的作品或过程 ➔ n.创造;作品;创作",
    "creative": "create (创造) + -ive ➔ 充满创造力的 ➔ adj.有创造力的;创新的",
    "credibility": "cred (相信) + -ibility ➔ 让人产生信任的可信度 ➔ n.可信度;可靠性",
    "crime": "cern (筛选/判决) ➔ 触犯法律受判决的罪行 ➔ n.犯罪;罪行",
    "criminal": "crime (罪行) + -inal ➔ 犯下罪行的人或行为 ➔ n.罪犯 adj.犯罪的",
    "crisis": "cri (决定/转折) + -sis ➔ 决定生死存亡的紧要关头 ➔ n.危机;紧要关头",
    "criterion": "crit (标准/判断) + -erion ➔ 用来挑选判断的标准 ➔ n.标准;准则 (复数: criteria)",
    "critical": "crit (判断/批判) + -ical ➔ 极具批判性或关键决定的 ➔ adj.批判的;关键的;危急的",
    "criticism": "critic (批评家) + -ism ➔ 发出的批评评论意见 ➔ n.批评;批判;评论",
    "criticize": "critic (批评家) + -ize ➔ 发起评论批判 ➔ v.批评;指责;评论",
    "crucial": "cruc (十字路口) + -ial ➔ 处在决定命运十字路口的 ➔ adj.至关重要的;决定性的",
    "cultivate": "cult (耕作/培养) + -ivate ➔ 耕耘土地培养人才 ➔ v.培养;耕作;陶冶",
    "culture": "cult (耕作/培育) + -ure ➔ 人类文明培育的成果 ➔ n.文化;文明;培养",
    "cure": "cur (关心/照料) ➔ 细心照料使其痊愈 ➔ v.治愈;医治 n.疗法;药物",
    "curious": "cur (关心/好奇) + -ious ➔ 极其关心想要探究的 ➔ adj.好奇的;奇特的新奇的",
    "current": "cur (跑/流动) + -ent ➔ 正在奔流运转中的 ➔ adj.当前的;流动的 n.水流;趋势",
    "custom": "cust (自己/习惯) + -om ➔ 长期形成的风俗习惯 ➔ n.风俗;习惯;海关",
    "customer": "custom (光顾习惯) + -er (人) ➔ 经常光顾买东西的人 ➔ n.顾客;客户",
    "damage": "dam (损失/伤害) + -age ➔ 造成的毁坏损失 ➔ n./v.损害;破坏;损失",
    "deadline": "dead (死) + line (线) ➔ 绝对不能跨越的最后死线 ➔ n.截止日期;最后期限",
    "debate": "de- (向下) + bate (打) ➔ 互相舌战击倒对方的辩论 ➔ n./v.辩论;争论",
    "decade": "deca (十) + -de ➔ 长达十年的时间段 ➔ n.十年;十年期",
    "decide": "de- (切断/向下) + cide (切) ➔ 斩钉截铁下定决心 ➔ v.决定;拿定主意",
    "decision": "decide (决定) + -ion ➔ 斩断犹豫后做出的抉择 ➔ n.决定;决议",
    "decisive": "decide (决定) + -ive ➔ 能够拍板决定果断的 ➔ adj.决定性的;果断的",
    "declare": "de- (加强) + clar (清楚) ➔ 大声说清楚公开宣告 ➔ v.宣称;宣布;申报",
    "decline": "de- (向下) + clin (倾斜) ➔ 向下滑落衰退 ➔ v./n.下降;衰退;拒绝",
    "decorate": "decor (美观/装饰) + -ate ➔ 打扮装点美化 ➔ v.装饰;装潢",
    "decrease": "de- (向下) + creas (生长) ➔ 反向生长减少 ➔ v./n.减少;降低",
    "dedicate": "de- (加强) + dic (宣誓/奉献) + -ate ➔ 庄严宣誓全心奉献 ➔ v.奉献;献出;致力于",
    "deduce": "de- (向下) + duce (引导) ➔ 顺藤摸瓜推导得出 ➔ v.推论;推断",
    "defeat": "de- (解开/取消) + feat (做) ➔ 打乱对方计划击败敌人 ➔ v./n.击败;战胜;挫败",
    "defend": "de- (向下) + fend (打击/防御) ➔ 挡住打击保护安全 ➔ v.保卫;防御;辩护",
    "defense": "defend (保卫) + -se ➔ 挡住攻击的防御工程 ➔ n.防御;保卫;防务",
    "deficit": "de- (缺乏) + fic (做) ➔ 资金不够做产生的亏空 ➔ n.赤字;亏空;赤字额",
    "define": "de- (加强) + fin (界限) ➔ 划分出清晰的含义界限 ➔ v.下定义;界定;解释",
    "definite": "define (界定) + -ite ➔ 划清界限明确无疑的 ➔ adj.明确的;确切的",
    "definitely": "definite (明确的) + -ly ➔ 毫无疑问毫无悬念地 ➔ adv.明确地;肯定地",
    "definition": "define (定义) + -ition ➔ 明确的含义阐释 ➔ n.定义;清晰度",
    "degree": "de- (向下) + gree (阶梯/步) ➔ 阶梯上的度数或学位 ➔ n.程度;度数;学位",
    "delay": "de- (向下) + lay (放置) ➔ 押后推迟放置 ➔ v./n.延迟;推迟;耽搁",
    "deliberate": "de- (加强) + liber (衡量/秤) + -ate ➔ 仔细称量深思熟虑的 ➔ adj.深思熟虑的;故意的",
    "delicate": "deli (诱人/精巧) + -cate ➔ 精致娇嫩易碎的 ➔ adj.精致的;微妙的;易碎的",
    "delicious": "deli (诱人/美味) + -cious ➔ 美味诱人的 ➔ adj.美味的;可口的",
    "delight": "de- (加强) + light (光/高兴) ➔ 内心充满光明愉悦 ➔ n.高兴;快乐 v.使高兴",
    "deliver": "de- (离开) + liver (自由) ➔ 释放送达物品 ➔ v.递送;交付;发表",
    "demand": "de- (加强) + mand (要求/命令) ➔ 强烈坚决要求 ➔ v./n.要求;需求",
    "democracy": "demo (民众) + cracy (统治/权力) ➔ 人民当家作主的制度 ➔ n.民主;民主制",
    "demonstrate": "de- (加强) + monstr (展示/表明) + -ate ➔ 现场演示证明 ➔ v.演示;说明;示威",
    "deny": "de- (向下) + ny (说不) ➔ 坚决否认拒绝承认 ➔ v.否认;拒绝",
    "depart": "de- (离开) + part (部分/区域) ➔ 离开原区域出发 ➔ v.离开;出发;启程",
    "department": "depart (分离开) + -ment ➔ 划分出来的部门科室 ➔ n.部门;系;局",
    "depend": "de- (向下) + pend (悬挂) ➔ 挂在对方身上依靠 ➔ v.依赖;依靠;取决于",
    "dependent": "depend (依赖) + -ent ➔ 挂在他人身上依靠的 ➔ adj.依赖的;取决于……的",
    "deposit": "de- (向下) + pos (放置) + -it ➔ 存入放下钱财保证金 ➔ v.存款;存放 n.存款;押金",
    "depress": "de- (向下) + press (压) ➔ 心理情绪被向下重压 ➔ v.使沮丧;使萧条",
    "deprive": "de- (剥夺) + prive (个人的/私有) ➔ 剥夺个人的财产权利 ➔ v.剥夺;使丧失",
    "derive": "de- (向下) + riv (河流/源头) ➔ 顺着水流源头引申出来 ➔ v.源于;衍生;获得",
    "describe": "de- (向下) + scribe (写) ➔ 详细记录描写下来 ➔ v.描述;形容",
    "deserve": "de- (加强) + serve (服务/值得) ➔ 付出了劳动理应得到 ➔ v.值得;应得",
    "design": "de- (出) + sign (标记/画图) ➔ 构思画出图纸标记 ➔ v./n.设计;图案;构想",
    "desire": "de- (离去) + sire (星辰) ➔ 仰望星空渴望获得 ➔ n./v.渴望;欲望;要求",
    "desperate": "de- (无/失去) + sper (希望) + -ate ➔ 毫无希望拼死一搏的 ➔ adj.绝望的;拼命的",
    "despite": "de- (向下) + spite (看) ➔ 轻视不顾阻碍 ➔ prep.尽管;不论",
    "destination": "de- (加强) + stin (站立/决定) + -ation ➔ 最终预定停脚的目的地 ➔ n.目的地;终点",
    "destroy": "de- (向下) + stroy (建造) ➔ 将建筑从上至下拆毁 ➔ v.毁坏;破坏;消灭",
    "detail": "de- (彻底) + tail (切割) ➔ 细致切碎的分项细节 ➔ n.细节;详情 v.详述",
    "detect": "de- (除去) + tect (盖子) ➔ 揭开盖子探明侦测 ➔ v.发现;侦测;察觉",
    "deter": "de- (向下) + ter (惊吓) ➔ 用震慑阻吓止步 ➔ v.威慑;吓住;阻止",
    "determine": "de- (加强) + termin (界限/终止) ➔ 下定决心划定界限 ➔ v.决定;决心;确定",
    "develop": "de- (解开) + velop (包裹) ➔ 揭开包裹逐步展开显现 ➔ v.发展;开发;培养",
    "device": "de- (出) + vic (分开/设计) ➔ 精巧发明设计出的装置 ➔ n.装置;设备;器具",
    "devote": "de- (加强) + vote (发誓/献出) ➔ 庄严发誓奉献全心 ➔ v.奉献;倾注;致力于",
    "diagnose": "dia- (穿过) + gnos (知道/识别) + -e ➔ 透过现象探明病因 ➔ v.诊断;判断",
    "diagram": "dia- (穿过) + gram (写/画) ➔ 用线条穿过画出的图表 ➔ n.图表;示意图",
    "dialect": "dia- (之间) + lect (说话/语言) ➔ 地区之间交流的本土方言 ➔ n.方言;地方话",
    "dialogue": "dia- (在……之间) + log (言语/交谈) ➔ 两个人之间的对白交谈 ➔ n.对话;对白",
    "dictate": "dict (说话/口授) + -ate ➔ 听写口授命令 ➔ v.口授;听写;命令",
    "dictionary": "dict (说话/词汇) + -ionary (集) ➔ 搜集所有查阅字词的宝典 ➔ n.字典;词典",
    "differ": "dis- (分开) + fer (带来) ➔ 带来不一样的分歧差异 ➔ v.不同;相异",
    "different": "differ (不同) + -ent ➔ 存在显著差异的 ➔ adj.不同的;有差异的",
    "difficult": "dis- (不) + fac (容易做) + -ult ➔ 不容易做成的 ➔ adj.困难的;难相处的",
    "digit": "digit (手指/计数字) ➔ 用10根手指计数的数字 ➔ n.数字;数位",
    "dignity": "dign (高贵/尊严) + -ity ➔ 高尚不可侵犯的尊严 ➔ n.尊严;高贵;庄严",
    "diminish": "di- (使) + min (小) + -ish ➔ 使体积或数量变小缩减 ➔ v.减少;缩减;贬低",
    "diploma": "di- (双) + plom (折叠) + -a ➔ 对折颁发的证书文凭 ➔ n.毕业文凭;学位证书",
    "diplomatic": "diploma (公文) + -tic ➔ 外交官拿着公文搞外交的 ➔ adj.外交的;圆滑的",
    "direct": "di- (分开) + rect (指引/直) ➔ 指引明确方向的 ➔ adj.直接的 v.指导;指挥",
    "direction": "direct (指引) + -ion ➔ 前进的方向指引 ➔ n.方向;指导;趋势",
    "disable": "dis- (剥夺/无) + able (能力) ➔ 剥夺能力使其残疾 ➔ v.使残废;使失去能力",
    "disadvantage": "dis- (相反) + advantage (优势) ➔ 处于劣势不利地位 ➔ n.不利条件;劣势",
    "disagree": "dis- (相反) + agree (同意) ➔ 观点抵触不同意 ➔ v.不同意;持异议",
    "disappear": "dis- (消除) + appear (出现) ➔ 出现的状态消失了 ➔ v.消失;不见",
    "disappoint": "dis- (取消) + appoint (任命/希望) ➔ 预期落空感到失望 ➔ v.使失望;使挫败",
    "disaster": "dis- (坏/坏星) + aster (星星) ➔ 凶星降临大难临头 ➔ n.灾难;灾祸;彻底失败",
    "discard": "dis- (扔掉) + card (扑克牌) ➔ 像抛弃废牌一样扔掉 ➔ v.丢弃;抛弃",
    "discharge": "dis- (卸下) + charge (装载) ➔ 卸下负担释放或出院 ➔ v./n.释放;解雇;排出",
    "discipline": "disc (学习/弟子) + -ipline ➔ 训练弟子遵守规矩 ➔ n.纪律;学科 v.训练",
    "disclose": "dis- (揭开) + close (关闭) ➔ 揭开原本关闭盖住的内容 ➔ v.揭露;公开;透露",
    "discount": "dis- (扣除) + count (计数) ➔ 扣掉一部分价格打折 ➔ n./v.折扣;打折",
    "discourage": "dis- (剥夺) + courage (勇气) ➔ 剥夺勇气使其泄气 ➔ v.使泄气;阻止;劝阻",
    "discover": "dis- (揭开) + cover (盖子) ➔ 掀开盖子发现新事物 ➔ v.发现;发觉",
    "discriminate": "dis- (分开) + crimin (筛选) + -ate ➔ 区分歧视区别对待 ➔ v.歧视;区别;辨别",
    "discuss": "dis- (分开) + cuss (敲打/震动) ➔ 深入探讨剖析 ➔ v.讨论;商讨",
    "disease": "dis- (离开) + ease (舒适) ➔ 离开舒适状态生病 ➔ n.疾病;弊病",
    "dismiss": "dis- (分开) + miss (发送/遣散) ➔ 遣散打发离开 ➔ v.解雇;解散;驳回",
    "disorder": "dis- (混乱) + order (秩序) ➔ 失去原有秩序混乱 ➔ n.混乱;失调;骚乱",
    "display": "dis- (展开) + play (折叠) ➔ 展开展现在面前 ➔ v./n.展示;显示;展览",
    "disposal": "dispose (处理) + -al ➔ 妥善清除处置 ➔ n.处理;处置;布置",
    "dispose": "dis- (分开) + pose (放置) ➔ 按规矩分开放置处理 ➔ v.处理;布置;安排",
    "dispute": "dis- (相反) + pute (思考/计算) ➔ 意见相反展开争执 ➔ v./n.争执;辩论;纠纷",
    "disrupt": "dis- (分开) + rupt (打破) ➔ 破扰原本的秩序中断 ➔ v.打乱;扰乱;使中断",
    "dissolve": "dis- (分开) + solve (解开) ➔ 溶解分散开来 ➔ v.溶解;融化;解散",
    "distance": "dis- (分开) + stance (站立) ➔ 两者分开站立的间距 ➔ n.距离;远方",
    "distant": "dis- (分开) + st (站立) + -ant ➔ 站得很遥远的 ➔ adj.遥远的;冷淡的",
    "distinct": "dis- (分开) + stinct (刺印/标记) ➔ 标记清晰截然不同的 ➔ adj.清晰的;独特的;截然不同的",
    "distinguish": "dis- (分开) + sting (刺/标记) + -uish ➔ 标出区别加以辨别 ➔ v.区分;辨别;使出众",
    "distribute": "dis- (分开) + tribute (给予) ➔ 分发给予大家 ➔ v.分发;分配;散布",
    "district": "dis- (分开) + strict (划界) ➔ 划分出来的行政区域 ➔ n.地区;行政区",
    "disturb": "dis- (加强) + turb (骚乱/混乱) ➔ 使其陷入打扰混乱 ➔ v.打扰;扰乱;使不安",
    "diverse": "di- (分开) + vers (转动) + -e ➔ 朝各个方向转变多样化的 ➔ adj.多种多样的;不同的",
    "diversity": "diverse (多样) + -ity ➔ 多样性多元化 ➔ n.多样性;多元化",
    "divert": "di- (偏离) + vert (转动) ➔ 转移转向注意力或水流 ➔ v.转移;使转向;使消遣",
    "divide": "di- (分开) + vide (分割) ➔ 切分开来分摊 ➔ v.分开;划分;除以",
    "divorce": "di- (分开) + vorc (转动) ➔ 夫妻分道扬镳离婚 ➔ n./v.离婚;分离",
    "document": "doc (教导/文件) + -ument ➔ 用于记载证明的文件 ➔ n.文档;文件 v.记录",
    "domain": "dom (房屋/领地) + -ain ➔ 所控制管辖的领地范围 ➔ n.领域;领地;域名",
    "domestic": "dom (房屋/家庭) + -estic ➔ 房屋内部或本国内部的 ➔ adj.国内的;家庭的;驯养的",
    "dominant": "domin (主宰/支配) + -ant ➔ 占主导支配地位的 ➔ adj.占优势的;主导的",
    "dominate": "domin (主宰/控制) + -ate ➔ 控制主宰大局 ➔ v.支配;主导;控制",
    "donate": "don (给予) + -ate ➔ 慷慨捐赠给予 ➔ v.捐赠;捐献",
    "drama": "dram (做/行动/戏剧) ➔ 舞台演出的剧本戏剧 ➔ n.戏剧;剧本;戏剧性事件",
    "dramatic": "drama (戏剧) + -tic ➔ 像戏剧一样跌宕起伏的 ➔ adj.戏剧性的;引人 sudden 的",
    "drought": "dry (干旱) + -th (名词) ➔ 长时间无雨的干旱灾害 ➔ n.干旱;旱灾",
    "duplicate": "du- (双/二) + plic (折叠) + -ate ➔ 对折复刻出一模一样的副本 ➔ v.复制 n.复制品",
    "durable": "dur (持久/坚硬) + -able ➔ 经久耐用的 ➔ adj.耐用的;持久的",
    "duration": "dur (持续) + -ation ➔ 持续经历的时间段 ➔ n.持续时间;期间",
    "duty": "due (应付/责任) + -ty ➔ 应当履行的职责义务 ➔ n.职责;义务;关税",
    "dynamic": "dynam (力量/动力) + -ic ➔ 充满活力和动能的 ➔ adj.充满活力的;动态的"
}

def derive_etymology(word, meaning, phrase):
    w_lower = word.lower().strip()
    
    # 1. Custom exact mapping
    if w_lower in CUSTOM_ETYMOLOGY:
        return CUSTOM_ETYMOLOGY[w_lower]
        
    # 2. Check Prefixes
    for pfx, label, pfx_desc in PREFIXES:
        if w_lower.startswith(pfx) and len(w_lower) > len(pfx) + 2:
            stem = w_lower[len(pfx):]
            return f"{label} + {stem} ➔ {pfx_desc} ➔ {meaning}"
            
    # 3. Check Suffixes
    for sfx, label, sfx_desc in SUFFIXES:
        if w_lower.endswith(sfx) and len(w_lower) > len(sfx) + 2:
            stem = w_lower[:-len(sfx)]
            return f"{stem} + {label} ➔ {sfx_desc} ➔ {meaning}"
            
    # 4. Fallback compound or root breakdown
    return f"核心词汇: {word} ➔ 音节拆解联想 ➔ 【高频短语: {phrase}】 ➔ {meaning}"

def process_target_words():
    with open('target_words_data.json', 'r', encoding='utf-8') as f:
        words_data = json.load(f)
        
    updated_count = 0
    custom_match_count = 0
    
    for item in words_data:
        word = item['word']
        meaning = item['meaning']
        phrase = item.get('phrase', '')
        
        etym = derive_etymology(word, meaning, phrase)
        item['etymology'] = etym
        updated_count += 1
        if word.lower().strip() in CUSTOM_ETYMOLOGY:
            custom_match_count += 1
            
    with open('target_words_data.json', 'w', encoding='utf-8') as f:
        json.dump(words_data, f, ensure_ascii=False, indent=2)
        
    print(f"Successfully processed {updated_count} words in target_words_data.json.")
    print(f"Custom detailed root decompositions applied to: {custom_match_count} words.")

if __name__ == '__main__':
    process_target_words()
