import json, re

# Specified words from 1-500 provided by user
selected_1_500 = [
    ("fail", "/feɪl/", "v. 失败;不及格;倒闭", "fail (费尔)", "fail the exam (考试不及格)", "fall (倒下) 演变而来 ➔ 跌倒、失败", "He failed the English test last week.", "他上周英语考试没及格。"),
    ("realize", "/ˈriː.ə.laɪz/", "v. 实现;意识到;领悟", "re - al - ize (瑞-阿-赖兹)", "realize dream (实现梦想)", "real (真实) + -ize (使……) ➔ 使变成真实的 ➔ 实现、意识到", "She realized that she had left her keys at home.", "她意识到自己把钥匙忘在家里了。"),
    ("recently", "/ˈriː.sənt.li/", "adv. 最近;近期地", "re - cent - ly (瑞-森特-利)", "recently published (最近出版的)", "recent (最近的) + -ly (副词后缀) ➔ 最近地", "I have recently started learning English.", "我最近开始学习英语了。"),
    ("scientist", "/ˈsaɪ.ən.tɪst/", "n. 科学家;科学工作者", "sci - en - tist (赛-恩-提斯特)", "famous scientist (著名科学家)", "sci (知道/科学) + -ist (人) ➔ 探索知识的人 ➔ 科学家", "The scientist spent years researching the new cure.", "这位科学家花了数年时间研究这种新疗法。"),
    ("spread", "/spred/", "v./n. 传播;蔓延;扩展", "spread (死普雷德)", "spread rumors (散布谣言)", "原始含义为伸展、铺开 ➔ 扩展、传播", "News of the event spread quickly.", "事件的消息迅速传开了。"),
    ("strength", "/streŋθ/", "n. 强度;力量;实力", "strength (死特伦斯)", "strengths and weaknesses (优势与劣势)", "strong (强壮的) + -th (抽象名词后缀) ➔ 力量、实力", "Practice will build up your physical strength.", "练习会增强你的体力。"),
    ("unusual", "/ʌnˈjuː.ʒu.əl/", "adj. 特别的;不寻常的;罕见的", "un - u - su - al (昂-优-热-口)", "unusual noise (特别的声音)", "un- (不) + usual (通常的) ➔ 不寻常的", "It is unusual for him to be late.", "他迟到是不寻常的。"),
    ("vehicle", "/ˈviː.ə.kəl/", "n. 车辆;工具;交通工具", "ve - hi - cle (维-黑-科尔)", "motor vehicle (机动车)", "vehy (运送) + -cle (器具) ➔ 运载工具 ➔ 车辆", "Emergency vehicles arrived at the scene quickly.", "救援车辆迅速赶到了现场。"),
    ("wild", "/waɪld/", "adj. 野生的;狂热的;自然生长的", "wild (歪尔德)", "wild animal (野生动物)", "源自古英语表示荒野的 ➔ 野生的", "Wild flowers grow along the river bank.", "野花沿着河岸生长。"),
    ("Egypt", "/ˈiː.dʒɪpt/", "n. 埃及", "E - gypt (伊-吉普特)", "ancient Egypt (古埃及)", "专有名词 ➔ 尼罗河畔的古国埃及", "Pyramids are famous landmarks of Egypt.", "金字塔是埃及著名的地标。"),
    ("Asia", "/ˈeɪ.ʒə/", "n. 亚洲", "A - sia (埃-热)", "East Asia (东亚)", "源自希腊语表示太阳升起之地 ➔ 东方/亚洲", "China is located in Asia.", "中国位于亚洲。"),
    ("Russia", "/ˈrʌʃ.ə/", "n. 俄罗斯", "Rus - sia (拉-申)", "Russian Federation (俄罗斯联邦)", "专有名词 ➔ 罗斯人的土地", "Russia is the largest country by land area.", "俄罗斯是按陆地面积计算最大的国家。"),
    ("afford", "/əˈfɔːrd/", "v. 提供;买得起;承担得起", "af - ford (额-佛德)", "can afford to (买得起/承担得起)", "af- (去) + forth (向前推) ➔ 能够推行得出资金 ➔ 承担得起", "I cannot afford to buy a new car right now.", "我眼下承担不起买新车的费用。"),
    ("ancient", "/ˈeɪn.ʃənt/", "adj. 古代的;古老的", "an - cient (埃恩-申特)", "ancient civilization (古代文明)", "ante (在……之前) + -ient (形容词) ➔ 久远以前的 ➔ 古老的", "They discovered ancient pottery in the cave.", "他们在洞穴里发现了古代陶器。"),
    ("consider", "/kənˈsɪd.ɚ/", "v. 考虑;认为;觉得", "con - sid - er (康-席-德尔)", "consider doing (考虑做)", "con- (共同) + sider (看星星/对星空思考) ➔ 认真斟酌 ➔ 考虑", "Please consider all options before making a decision.", "做决定前请考虑所有选项。"),
    ("eventually", "/ɪˈven.tʃu.əl.i/", "adv. 最后;终于", "e - ven - tu - al - ly (伊-文-出-额-利)", "eventually succeed (最终成功)", "event (事件) + -ual + -ly ➔ 事件发展到最后的结局 ➔ 终于", "He eventually achieved his goal through hard work.", "他最终通过努力实现了目标。"),
    ("exercise", "/ˈek.sɚ.saɪz/", "n./v. 锻炼;练习", "ex - er - cise (埃克-色-赛兹)", "take exercise (进行锻炼)", "ex- (驱动出来) + arcere (约束/训练) ➔ 释放体能训练 ➔ 锻炼", "Regular exercise is good for your health.", "定期锻炼对健康有益。"),
    ("extreme", "/ɪkˈstriːm/", "n./adj. 极端;极限;极度的", "ex - treme (伊克-死特林姆)", "extreme weather (极端天气)", "extra (超出) + -eme (最高级) ➔ 超出最外边界的 ➔ 极端的", "The region experiences extreme cold in winter.", "该地区冬季气候极为寒冷。"),
    ("medicine", "/ˈmed.ə.sən/", "n. 医学;药", "med - i - cine (美-蒂-席恩)", "take medicine (吃药)", "med (医治/衡量) + -icine (学问/药物) ➔ 治病的药 ➔ 医学/药", "Remember to take your medicine after meals.", "记得饭后服药。"),
    ("national", "/ˈnæʃ.ən.əl/", "adj. 国家的;民族的;全国的", "na - tion - al (拿-申-诺尔)", "national park (国家公园)", "nation (国家) + -al (形容词后缀) ➔ 国家的", "National day is a public holiday.", "国庆日是法定假日。"),
    ("natural", "/ˈnætʃ.ɚ.əl/", "adj. 自然的;天然的;正常的", "nat - u - ral (拿-出-柔)", "natural environment (自然环境)", "nat (出生/天生) + -ural ➔ 天生存在的 ➔ 自然的", "Fresh fruit is rich in natural sugar.", "新鲜水果富含天然糖分。"),
    ("ocean", "/ˈoʊ.ʃən/", "n. 海洋", "o - cean (欧-申)", "Pacific Ocean (太平洋)", "源自希腊神话大洋神 Oceanus ➔ 广阔无垠的海洋", "The island is surrounded by the ocean.", "这个岛屿被海洋环绕。"),
    ("overall", "/ˌoʊ.vɚˈɑːl/", "adv./adj. 全部;总计;一般来说", "over - all (欧-沃-奥尔)", "overall trend (总体趋势)", "over (覆盖) + all (全部) ➔ 覆盖整体地 ➔ 总体的", "The overall performance of the team was great.", "团队的总体表现非常棒。"),
    ("pressure", "/ˈpreʃ.ɚ/", "n. 压力;压强;挤压", "pres - sure (普瑞-舍)", "under pressure (承受压力)", "press (压) + -ure (名词后缀) ➔ 施加作用力 ➔ 压力", "High blood pressure is a serious health issue.", "高血压是一个严重的健康问题。"),
    ("prevent", "/prɪˈvent/", "v. 阻止;阻碍;阻挠", "pre - vent (普瑞-文特)", "prevent A from B (阻止A做B)", "pre- (在前面) + vent (走) ➔ 提前走到前面挡住路 ➔ 阻止", "Vaccines help prevent dangerous diseases.", "疫苗有助于预防危险疾病。"),
    ("quite", "/kwaɪt/", "adv. 很;相当;非常", "quite (快特)", "quite good (相当不错)", "quit (彻底释放/完全) 的变体 ➔ 相当地、彻底地", "The test was quite difficult.", "这次考试相当难。"),
    ("scene", "/siːn/", "n. 现场;景象;情景", "scene (斯因)", "behind the scenes (幕后)", "源自希腊语 skene (舞台背景) ➔ 景象、现场", "Firefighters quickly arrived at the scene.", "消防员迅速赶到了现场。"),
    ("strange", "/streɪndʒ/", "adj. 奇怪的;奇特的;异样的", "strange (死特润奇)", "strange noise (奇怪的噪音)", "extraneus (外来的) ➔ 不熟悉的、奇怪的", "I heard a strange sound outside the door.", "我听到门外有奇怪的声音。"),
    ("succeed", "/səkˈsiːd/", "v. 成功;接替;继承", "suc - ceed (色克-斯伊斯)", "succeed in doing (成功做成)", "sub- (在后面) + ceed (走) ➔ 顺着走下去、达成 ➔ 成功", "If you work hard, you will succeed.", "如果你努力工作，你就会成功。"),
    ("thought", "/θɑːt/", "n. 思想;思考;想法", "thought (索特)", "thought of (想法)", "think (思考) 的过去式与名词形式 ➔ 思考、想法", "She was deep in thought.", "她陷入了沉思。"),
    ("weak", "/wiːk/", "adj. 虚弱的;无力的;差的", "weak (威克)", "feel weak (感到虚弱)", "源自古诺斯语软化/弯曲 ➔ 缺乏力量的 ➔ 虚弱的", "His voice sounded weak over the phone.", "他在电话里的声音显得很虚弱。"),
    ("above", "/əˈbʌv/", "prep./adv. 在……上面;高于", "a - bove (额-巴夫)", "above average (高于平均水平)", "a- (在) + bove (上方) ➔ 在更高的位置", "The sun rose above the horizon.", "太阳升起了地平线。"),
    ("activity", "/ækˈtɪv.ə.ti/", "n. 活动;行动", "ac - tiv - i - ty (埃克-提-维-蒂)", "outdoor activity (户外活动)", "act (行动) + -ive + -ity ➔ 积极的行动 ➔ 活动", "Swimming is a popular summer activity.", "游泳是一项受欢迎的夏季活动。"),
    ("affect", "/əˈfekt/", "v. 影响;感动;假装", "af - fect (额-费克特)", "affect health (影响健康)", "ad- (去) + fect (做) ➔ 去作用于某事物 ➔ 影响", "Climate change will affect farming worldwide.", "气候变化将影响全球农业。"),
    ("against", "/əˈɡenst/", "prep. 反对;违背;靠着", "a - gainst (额-根斯特)", "against the rule (违反规则)", "again (相对) + -st (方向) ➔ 朝相反方向推 ➔ 反对、靠着", "She leaned against the wall.", "她靠在墙上。"),
    ("alike", "/əˈlaɪk/", "adj./adv. 相似的;同样地", "a - like (额-赖克)", "look alike (看起来很像)", "a- (处于……状态) + like (相像) ➔ 状态相近的 ➔ 相似的", "The twin sisters look remarkably alike.", "这对双胞胎姐妹看起来非常相似。"),
    ("amateur", "/ˈæm.ə.tʃɚ/", "n./adj. 业余爱好者;业余的", "am - a - teur (埃-么-特尔)", "amateur photographer (业余摄影师)", "amat (爱) + -eur (人) ➔ 出于爱好做某事的人 ➔ 业余爱好者", "He is an amateur painter.", "他是一位业余画家。"),
    ("amusement", "/əˈmjuːz.mənt/", "n. 愉悦;娱乐;消遣", "a - muse - ment (额-缪斯-蒙特)", "amusement park (游乐园)", "a- (使得) + muse (沉思/发呆) ➔ 引人发笑消遣 ➔ 娱乐", "The kids played games for their own amusement.", "孩子们玩游戏自乐。"),
    ("army", "/ˈɑːr.mi/", "n. 军队;陆军", "ar - my (阿-米)", "join the army (参军)", "arm (武器) + -y (集合名词) ➔ 装备武装的人群 ➔ 军队", "He joined the army after graduation.", "他毕业后参军了。"),
    ("attack", "/əˈtæk/", "v./n. 攻击;进攻", "at - tack (额-泰克)", "heart attack (心脏病发作 / 攻击)", "at- (去) + tack (钉/刺) ➔ 去刺击对方 ➔ 攻击", "The cat was ready to attack the mouse.", "那只猫准备发起攻击。"),
    ("attentively", "/əˈten.t̬ɪv.li/", "adv. 专注地;聚精会神地", "at - ten - tive - ly (额-滕-提夫-利)", "listen attentively (专注倾听)", "ad- (去) + tent (伸展) + -ively ➔ 把耳朵伸过去听 ➔ 专注地", "The students listened attentively to the lecture.", "同学们聚精会神地听讲座。"),
    ("author", "/ˈɑː.θɚ/", "n. 作者;作家", "au - thor (奥-色)", "bestselling author (畅销书作家)", "aug (创造/增加) + -or (人) ➔ 创作者 ➔ 作者", "She is the author of several books.", "她是几本书的作者。"),
    ("average", "/ˈæv.ɚ.ɪdʒ/", "adj./n. 平均的;平均数", "av - er - age (埃-沃-瑞奇)", "above average (高于平均水平)", "haverie (海损平摊分扣) ➔ 平摊分担的数值 ➔ 平均数", "His test scores are above average.", "他的考试成绩高于平均水平。"),
    ("aware", "/əˈwer/", "adj. 意识到的;察觉到的", "a - ware (额-维尔)", "be aware of (意识到)", "a- (处于) + ware (警觉/看顾) ➔ 处于警觉警觉状态 ➔ 意识到的", "Are you aware of the risks involved?", "你意识到其中涉及的风险了吗？"),
    ("barbecue", "/ˈbɑːr.bə.kjuː/", "n./v. 烧烤;烤肉", "bar - be - cue (巴-比-扣)", "outdoor barbecue (户外烧烤)", "源自海地土著语木架烤肉 ➔ 烧烤", "We had a barbecue in the backyard.", "我们在后院举行了烧烤。"),
    ("belongings", "/bɪˈlɑːŋ.ɪŋz/", "n. 财物;所有物", "be - long - ings (比-隆-凝兹)", "personal belongings (个人随身物品)", "be- (关于) + long (属于) + -ings ➔ 归属于自己的东西 ➔ 财物", "Please take your personal belongings with you.", "请带好您的个人随身物品。"),
    ("beneficial", "/ˌben.əˈfɪʃ.əl/", "adj. 有益的;有利的", "ben - e - fi - cial (本-尼-非-手)", "beneficial to (对……有益)", "bene (好) + fic (做) + -ial ➔ 做了好事有帮助的 ➔ 有益的", "Exercise is beneficial to health.", "运动对健康有益。"),
    ("benefit", "/ˈben.ə.fɪt/", "n./v. 利益;好处;受益", "ben - e - fit (本-尼-费特)", "benefit from (受益于)", "bene (好) + fit (做) ➔ 带来的好事 ➔ 好处/利益", "The new law will benefit many families.", "新法律将使许多家庭受益。"),
    ("blow", "/bloʊ/", "v./n. 吹;刮风;爆炸", "blow (布楼)", "blow out (吹灭)", "原始模仿风吹气声 ➔ 吹刮", "A strong wind began to blow.", "刮起了强风。"),
    ("brake", "/breɪk/", "n./v. 刹车;制动器", "brake (布雷克)", "apply the brake (踩刹车)", "break (破碎/打断) 同源 ➔ 打断运动的装置 ➔ 刹车", "He stepped on the brake to stop the car.", "他踩下刹车使车停住。"),
    ("breath", "/breθ/", "n. 呼吸的空气;气息", "breath (布雷斯)", "take a deep breath (深呼吸)", "源自古英语蒸发/气息 ➔ 呼吸", "Take a deep breath and relax.", "深呼吸，放松一下。"),
    ("campaign", "/kæmˈpeɪn/", "n./v. 运动;战役;活动", "cam - paign (看-佩恩)", "advertising campaign (广告宣传运动)", "camp (野外战场) + -aign ➔ 在野外展开的系列行动 ➔ 运动/战役", "The marketing campaign was a huge success.", "营销活动取得了巨大的成功。"),
    ("carry", "/ˈkær.i/", "v. 携带;搬运;运送", "car - ry (卡-瑞)", "carry on (继续做)", "car (车/载具) + -y ➔ 用车运载 ➔ 携带、搬运", "Can you help me carry this box?", "你能帮我搬一下这个箱子吗？"),
    ("century", "/ˈsen.tʃə.ri/", "n. 世纪;一百年", "cen - tu - ry (森-秋-瑞)", "21st century (21世纪)", "cent (一百) + -ury (名词后缀) ➔ 一百年 ➔ 世纪", "We live in the twenty-first century.", "我们生活在二十一世纪。"),
    ("charity", "/ˈtʃær.ə.ti/", "n. 慈善机构;慈善;赈济", "char - i - ty (查-瑞-蒂)", "charity event (慈善活动)", "char (亲爱/仁慈) + -ity ➔ 怀着仁爱之心施舍 ➔ 慈善", "She donated money to a local charity.", "她向当地一家慈善机构捐了款。"),
    ("civil", "/ˈsɪv.əl/", "adj. 公民的;国民的;文职的", "civ - il (席-沃)", "civil servant (公务员)", "civis (公民/城邦居民) + -il ➔ 公民的", "He works as a civil servant in the government.", "他在政府部门担任公务员。"),
    ("claim", "/kleɪm/", "v./n. 声称;宣称;索赔", "claim (克雷姆)", "claim that (声称)", "clam/claim (大声呼喊) ➔ 站出来呼喊主张 ➔ 声称/索取", "He claimed that he knew nothing about the plan.", "他声称对该计划一无所知。"),
    ("climate", "/ˈklaɪ.mət/", "n. 气候;风气", "cli - mate (克赖-莫特)", "climate change (气候变化)", "cli (倾斜) + -mate ➔ 太阳倾斜角度决定的天候 ➔ 气候", "The tropical climate is hot and humid.", "热带气候炎热潮湿。"),
    ("comfort", "/ˈkʌm.fɚt/", "n./v. 安慰;舒适", "com - fort (康-佛特)", "comfort zone (舒适区)", "com- (加强) + fort (强壮) ➔ 给人以坚强支柱 ➔ 安慰、舒适", "Her warm words brought great comfort to me.", "她温暖的话语给我带来了极大的安慰。"),
    ("common", "/ˈkɑː.mən/", "adj. 常见的;普通的;共同的", "com - mon (康-蒙)", "common sense (常识)", "com- (共同) + munis (承担) ➔ 大家共同享有的 ➔ 普通的/共同的", "Snow is very common in winter here.", "这里冬天下雪是很常见的。"),
    ("community", "/kəˈmjuː.nə.ti/", "n. 社区;社团;群落", "com - mu - ni - ty (康-缪-尼-蒂)", "community service (社区服务)", "com- (共同) + mun (公共职责) + -ity ➔ 共同生活的圈子 ➔ 社区", "They organize many community events.", "他们组织了许多社区活动。"),
    ("conclusion", "/kənˈkluː.ʒən/", "n. 结论;推论;结尾", "con - clu - sion (康-克鲁-热恩)", "reach a conclusion (得出结论)", "con- (强调) + clud (关上/结束) + -sion ➔ 讨论关门结束时的定案 ➔ 结论", "We reached a positive conclusion.", "我们得到了积极的结论。"),
    ("considering", "/kənˈsɪd.ɚ.ɪŋ/", "prep./conj. 考虑到;鉴于", "con - sid - er - ing (康-席-德-林)", "considering that (考虑到)", "consider (考虑) + -ing (介词化后缀) ➔ 考虑到", "Considering his age, he did very well.", "考虑到他的年龄，他做得非常好。"),
    ("correct", "/kəˈrekt/", "adj./v. 正确的;纠正", "cor - rect (康-瑞克特)", "correct answer (正确答案)", "com- (完全) + rect (直/正) ➔ 彻底纠正变直 ➔ 正确的", "Please check your answers to make sure they are correct.", "请检查您的答案以确保正确。"),
    ("counter", "/ˈkaʊn.t̬ɚ/", "n./v. 柜台;计数器;反驳", "coun - ter (考-特尔)", "kitchen counter (厨房柜台)", "contra (相对/相反) + -er ➔ 站在对面交易的桌案 ➔ 柜台/反驳", "She set her coffee cup down on the counter.", "她把咖啡杯放在柜台上。"),
    ("courage", "/ˈkɝː.ɪdʒ/", "n. 勇气;勇敢", "cour - age (科-瑞奇)", "have the courage to (有勇气做)", "cour/cor (心) + -age ➔ 内心坚定强悍 ➔ 勇气", "It takes courage to speak the truth.", "说出真相需要勇气。"),
    ("creative", "/kriˈeɪ.t̬ɪv/", "adj. 有创造力的;创意的", "cre - a - tive (克里-埃-提夫)", "creative thinking (创造性思维)", "crea (产生/创造) + -tive (形容词) ➔ 善于创造的 ➔ 有创造力的", "She is known for her creative design ideas.", "她以富有创意的设计理念著称。"),
    ("cultivate", "/ˈkʌl.tə.veɪt/", "v. 培养;培育;耕作", "cul - ti - vate (卡-提-维特)", "cultivate habits (培养习惯)", "cult (耕种/关心) + -ivate ➔ 灌溉栽培 ➔ 培养/耕作", "Parents should cultivate good reading habits in children.", "父母应当培养孩子的良好阅读习惯。"),
    ("cure", "/kjʊr/", "v./n. 治愈;治疗;疗法", "cure (扣尔)", "cure disease (治愈疾病)", "cura (关照/护理) ➔ 精心护理使康复 ➔ 治愈", "Scientists are working hard to find a cure.", "科学家们正努力寻找治愈方法。"),
    ("daylight", "/ˈdeɪ.laɪt/", "n. 日光;白昼", "day - light (戴-赖特)", "in broad daylight (在大白天的光线中)", "day (白天) + light (光) ➔ 太阳射出的光线 ➔ 日光", "The room gets plenty of natural daylight.", "这间屋子有充足的自然采光。"),
    ("deal", "/diːl/", "v./n. 处理;打交道;交易", "deal (蒂尔)", "deal with (处理/应对)", "原意为分发/分配 ➔ 交易、处理", "We need to deal with this problem immediately.", "我们需要立即处理这个问题。"),
    ("decorate", "/ˈdek.ə.reɪt/", "v. 装饰;装潢", "dec - o - rate (戴-科-雷特)", "decorate room (装饰房间)", "decor (美观/体面) + -ate ➔ 使美观 ➔ 装饰", "They decorated the christmas tree with lights.", "他们用灯饰装点了圣诞树。"),
    ("defend", "/dɪˈfend/", "v. 防御;保卫;辩护", "de - fend (蒂-分德)", "defend against (抵御)", "de- (远离) + fend (打击) ➔ 打击击退侵犯 ➔ 保卫/防御", "Soldiers were trained to defend the nation.", "士兵们接受训练以保卫国家。"),
    ("definite", "/ˈdef.ən.ət/", "adj. 明确的;肯定的;确切的", "def - i - nite (戴-非-内特)", "definite answer (明确的回答)", "de- (强调) + fin (界限) + -ite ➔ 划清界限毫不含糊 ➔ 明确的", "We need a definite date for the meeting.", "我们需要会议确切的日期。"),
    ("deliberate", "/dɪˈlɪb.ɚ.ət/", "adj./v. 故意的;深思熟虑的", "de - lib - er - ate (蒂-利-伯-雷特)", "deliberate choice (深思熟虑的选择)", "de- (仔细) + liber (天平) + -ate ➔ 用天平仔细称量 ➔ 深思熟虑的/故意的", "It was a deliberate attempt to hide the truth.", "这是一次掩盖真相的蓄意尝试。"),
    ("deserve", "/dɪˈzɝːv/", "v. 值得;应得;应受", "de - serve (蒂-泽夫)", "deserve respect (值得尊重)", "de- (完全) + serve (服务/付出) ➔ 付出了足够的努力 ➔ 应得/值得", "You worked hard and deserve to succeed.", "你努力工作，值得获得成功。"),
    ("difference", "/ˈdɪf.ɚ.əns/", "n. 差异;差别;不同之处", "dif - fer - ence (蒂-弗-伦斯)", "make a difference (产生影响/改变)", "dis- (分开) + fer (带来) + -ence ➔ 产生不同走向 ➔ 差异", "Can you tell the difference between the two?", "你能说出这两者之间的差异吗？"),
    ("dig", "/dɪɡ/", "v. 挖掘;挖;凿", "dig (蒂格)", "dig a hole (挖坑)", "拟声词动作 ➔ 用铲凿土 ➔ 挖掘", "Dogs like to dig holes in the garden.", "狗喜欢在花园里挖洞。"),
    ("direction", "/daɪˈrek.ʃən/", "n. 方向;方位;指点", "di - rec - tion (代-瑞克-申)", "in the right direction (朝正确的方向)", "dis- (分开) + rect (指导/直) + -ion ➔ 引导指引的路线 ➔ 方向", "Which direction are we heading in?", "我们正在朝着哪个方向前进？"),
    ("director", "/daɪˈrek.tɚ/", "n. 经理;董事;导演", "di - rec - tor (代-瑞克-特尔)", "movie director (电影导演)", "direct (指导) + -or (人) ➔ 掌舵指导全局的人 ➔ 导演/经理", "The movie director won an award.", "这位电影导演获得了奖项。"),
    ("discover", "/dɪˈskʌv.ɚ/", "v. 发现;找到;发觉", "dis - cov - er (蒂-死卡-沃)", "discover truth (发现真相)", "dis- (揭开/除去) + cover (盖子) ➔ 掀开盖子 ➔ 发现", "Scientists discovered a new planet.", "科学家们发现了一颗新行星。"),
    ("discussion", "/dɪˈskʌʃ.ən/", "n. 讨论;商讨", "dis - cus - sion (蒂-死卡-申)", "have a discussion (展开讨论)", "dis- (分开) + cut (敲击) + -ion ➔ 碰撞交流看法 ➔ 讨论", "We had a lively discussion about the project.", "我们对该项目展开了热烈的讨论。"),
    ("disease", "/dɪˈziːz/", "n. 疾病;弊端", "dis - ease (蒂-兹伊斯)", "prevent disease (预防疾病)", "dis- (缺乏/否定) + ease (舒适) ➔ 身体失去舒适状态 ➔ 疾病", "Exercise helps protect against heart disease.", "运动有助于预防心脏病。"),
    ("distinguish", "/dɪˈstɪŋ.ɡwɪʃ/", "v. 区别;辨别;分清", "dis - tin - guish (蒂-死听-格威什)", "distinguish between (区分两者)", "dis- (分开) + stinguere (刺标记) ➔ 戳印分别开来 ➔ 区分", "It is important to distinguish fact from fiction.", "区分事实与虚构至关重要。"),
    ("domestic", "/dəˈmes.tɪk/", "adj. 本国的;国内的;家庭的", "do - mes - tic (多-美斯-提克)", "domestic market (国内市场)", "dom (房屋/家) + -estic ➔ 属于家庭或国内的 ➔ 国内的/家庭的", "Domestic flights depart from terminal one.", "国内航班从一号航站楼起飞。"),
    ("due", "/duː/", "adj. 到期的;应付的;由于", "due (杜)", "due to (由于)", "debere (欠下) ➔ 应当交付归还的 ➔ 到期的/由于", "The payment is due next Friday.", "付款将于下周五到期。"),
    ("dust", "/dʌst/", "n. 灰尘;粉尘;沙土", "dust (达斯特)", "remove dust (清除灰尘)", "原始意为吹散的气体粒子 ➔ 灰尘", "A thick layer of dust covered the table.", "桌上蒙着一层厚厚的灰尘。"),
    ("effort", "/ˈef.ɚt/", "n. 努力;力气;尽力", "ef - fort (埃-佛特)", "make an effort (做出努力)", "ex- (出来) + fort (力量) ➔ 把力量使出来 ➔ 努力", "Please make an effort to arrive on time.", "请努力争取按时到达。"),
    ("else", "/els/", "adv. 其他;另外;否则", "else (埃尔斯)", "anything else (还需要别的吗)", "源自古英语异样 ➔ 其他、另外", "Is there anything else I can help with?", "还有什么其他我可以帮忙的吗？"),
    ("emotional", "/ɪˈmoʊ.ʃən.əl/", "adj. 情感的;情绪的", "e - mo - tion - al (伊-摩-申-诺尔)", "emotional support (情感支持)", "ex- (出来) + mot (移动/波动) + -ional ➔ 情绪波动喷发 ➔ 情感的", "Music can trigger strong emotional responses.", "音乐能引发强烈的情感共鸣。"),
    ("entrance", "/ˈen.trəns/", "n. 入口处;进入许可", "en - trance (埃恩-特伦斯)", "main entrance (正门入口)", "enter (进入) + -ance ➔ 迈步走入的位置 ➔ 入口处", "Wait for me at the main entrance.", "在正门入口处等我。"),
    ("expect", "/ɪkˈspekt/", "v. 期望;预计;期待", "ex - spect (伊克-死佩克特)", "expect result (期待结果)", "ex- (向外) + spect (看) ➔ 翘首以盼向外看 ➔ 期待", "We expect rain later this evening.", "我们预计今晚晚些时候会有雨。"),
    ("experience", "/ɪkˈspɪr.i.əns/", "v./n. 体会;体验;经历;经验", "ex - spir - i - ence (伊克-死皮-瑞-恩斯)", "work experience (工作经验)", "ex- (出来) + peri (尝试) + -ence ➔ 亲自尝试出来的体会 ➔ 经历/经验", "She has years of experience in teaching.", "她在教学方面有多年经验。"),
    ("extra", "/ˈek.strə/", "adv./adj. 额外;特别;另外", "ex - tra (埃克-死特拉)", "extra cost (额外费用)", "exter (外部) ➔ 在正常额度之外附加的 ➔ 额外的", "They charged an extra fee for delivery.", "他们收取了额外的配送费。"),
    ("extremely", "/ɪkˈstriːm.li/", "adv. 非常;极其;极端地", "ex - treme - ly (伊克-死特林姆-利)", "extremely important (极其重要)", "extreme (极端的) + -ly (副词) ➔ 极其地", "The weather was extremely hot yesterday.", "昨天天气极其炎热。"),
    ("fame", "/feɪm/", "n./v. 名声;声誉;名气", "fame (飞姆)", "hall of fame (名人堂)", "fari (说话/传颂) ➔ 口口相传的声誉 ➔ 名声", "He achieved fame through his poetry.", "他通过诗歌获得了名声。"),
    ("familiar", "/fəˈmɪl.i.ɚ/", "adj. 熟悉的;通晓的", "fa - mil - i - ar (法-米-利-尔)", "be familiar with (对……熟悉)", "family (家庭) + -ar ➔ 像家人一样亲近了解 ➔ 熟悉的", "Her face looks familiar to me.", "她的面孔对我来说看起来很眼熟。"),
    ("famous", "/ˈfeɪ.məs/", "adj. 著名的;出名的", "fa - mous (飞-摩斯)", "famous for (因……而出名)", "fame (名声) + -ous (充满) ➔ 声名远播的 ➔ 著名的", "The city is famous for its delicious food.", "这座城市以美食闻名。"),
    ("fight", "/faɪt/", "v./n. 战斗;打架", "fight (法伊特)", "fight for (为……而战)", "源自古英语搏斗 ➔ 战斗、打架", "They decided to fight for their rights.", "他们决定为自己的权利而战。"),
    ("fill", "/fɪl/", "v./n. 装满;充满", "fill (飞尔)", "fill with (充满)", "full (满的) 衍生动词 ➔ 填满", "Please fill the glass with water.", "请在玻璃杯里装满水。"),
    ("finally", "/ˈfaɪ.nəl.i/", "adv. 终于;最终;最后", "fi - nal - ly (法伊-诺-利)", "finally arrive (终于到达)", "final (最终的) + -ly (副词) ➔ 最终地", "The train finally arrived after a long delay.", "火车在漫长的延误后终于到了。"),
    ("fortunately", "/ˈfɔːr.tʃə.nət.li/", "adv. 幸运地;幸好", "for - tu - nate - ly (佛-秋-内特-利)", "fortunately survived (幸运幸存)", "fortune (运气) + -ately ➔ 幸运地", "Fortunately, no one was hurt in the crash.", "幸运的是，撞车事故中无人受伤。"),
    ("frighten", "/ˈfraɪ.tən/", "v. 使惊吓;使惊恐", "fright - en (法赖-滕)", "frighten someone (吓坏某人)", "fright (恐怖) + -en (使变成) ➔ 使产生恐惧 ➔ 吓唬", "Loud noises frighten small children.", "巨大的噪音会吓坏幼儿。"),
    ("frightening", "/ˈfraɪ.tən.ɪŋ/", "adj. 引起恐惧的;骇人的", "fright - en - ing (法赖-滕-凝)", "frightening experience (骇人的经历)", "frighten + -ing ➔ 令人惊恐的", "It was a frightening story.", "那是一个让人害怕的故事。"),
    ("further", "/ˈfɝː.ðɚ/", "adv./adj. 进一步;此外;更远", "fur - ther (佛-泽尔)", "further information (进一步的信息)", "fore (前) 比较级 ➔ 更远、进一步", "Contact us for further information.", "如需进一步信息请联系我们。"),
    ("gentle", "/ˈdʒen.t̬əl/", "adj. 温柔的;小心的", "gen - tle (杰-托尔)", "gentle breeze (和煦的微风)", "gens (出身名门/受教养) ➔ 举止文明有礼 ➔ 温柔的", "Be gentle with the baby.", "对婴儿要温柔小心。"),
    ("grass", "/ɡræs/", "n. 草;草地", "grass (格拉斯)", "green grass (绿草)", "grow (生长) 同源 ➔ 遍布生长的植物 ➔ 草", "Cows were grazing on the fresh grass.", "牛群在吃新鲜的青草。"),
    ("gratitude", "/ˈɡræt̬.ə.tuːd/", "n. 感激之情;感谢", "grat - i - tude (格拉-提-特尤德)", "express gratitude (表达感激)", "gratus (感激/令人愉悦) + -itude ➔ 感激之情", "I would like to express my sincere gratitude.", "我想表达我真挚的感谢。"),
    ("greenhouse", "/ˈɡriːn.haʊs/", "n. 温室;暖房", "green - house (格林-豪斯)", "greenhouse effect (温室效应)", "green (绿色/植物) + house (房屋) ➔ 保温种植物的房子 ➔ 温室", "Tomatoes are grown in a greenhouse.", "西红柿是在温室里种植的。"),
    ("grey", "/ɡreɪ/", "adj./n. 灰色的;灰暗的", "grey (格雷)", "grey sky (阴沉的天空)", "源自日耳曼语灰色 ➔ 灰暗的", "The sky looked grey and stormy.", "天空看起来灰暗且风暴将至。"),
    ("guide", "/ɡaɪd/", "n./v. 指南;向导;指引", "guide (盖德)", "tourist guide (导游)", "源自古法语观察/引领 ➔ 向导、指南", "The local guide took us through the forest.", "当地导游带我们穿越了森林"),
    ("hall", "/hɑːl/", "n. 大厅;礼堂;门厅", "hall (霍尔)", "town hall (市政厅)", "源自古英语大屋/覆盖 ➔ 大厅", "Concerts are held in the main hall.", "音乐会在主大厅举行。"),
    ("hardly", "/ˈhɑːrd.li/", "adv. 几乎没有;几乎不", "hard - ly (哈德-利)", "hardly ever (几乎很少)", "hard (艰难地) + -ly (反向修饰) ➔ 极难达到 ➔ 几乎没有", "I could hardly believe my eyes.", "我几乎不能相信自己的眼睛。"),
    ("identical", "/aɪˈden.t̬ə.kəl/", "adj. 完全同样的;同一的", "i - den - ti - cal (爱-登-提-口)", "identical twin (同卵双胞胎)", "idem (同一) + -tical ➔ 完全一样的", "The twins were wearing identical outfits.", "这对双胞胎穿着用料完全一样的服装。"),
    ("increase", "/ɪnˈkriːs/", "v./n. 增加;增长", "in - crease (因-克里斯)", "increase rapidly (迅速增长)", "in- (使/向内) + crease/cresc (生长) ➔ 向内持续生长 ➔ 增加", "The company aims to increase sales.", "公司旨在增加销售额。"),
    ("indoors", "/ˌɪnˈdɔːrz/", "adv. 在室内;进入户内", "in - doors (因-多斯)", "stay indoors (呆在室内)", "in (在……内) + doors (门) ➔ 进门之内 ➔ 在室内", "It was raining, so we played indoors.", "外面在下雨，所以我们在室内玩。"),
    ("injury", "/ˈɪn.dʒɚ.i/", "n. 损伤;挫伤;伤害", "in - ju - ry (因-哲-瑞)", "head injury (头部损伤)", "in- (否定) + jus/jur (正义/完整) + -y ➔ 身体受到破坏 ➔ 损伤", "He suffered a serious knee injury.", "他的膝盖严重受伤。")
]

print(f"Prepared {len(selected_1_500)} user-selected words from 1-500 list.")
